Repository learning-process/ppc-2024-autumn, pull requests merged in 2024-12, with the labels that each got.

#255 Будажапова Екатерина. Задача 1. Вариант 23. Частота символа в строке.
  tasks/mpi/budazhapova_e_count_freq_character/func_tests/count_freq_character_func_test_mpi.cpp
  tasks/mpi/budazhapova_e_count_freq_character/include/count_freq_character_mpi_header.hpp
  tasks/mpi/budazhapova_e_count_freq_character/perf_tests/count_freq_character_pref_test_mpi.cpp
  tasks/mpi/budazhapova_e_count_freq_character/src/count_freq_character_mpi.cpp
  tasks/seq/budazhapova_e_count_freq_character/func_tests/count_freq_character_func_tests.cpp
  tasks/seq/budazhapova_e_count_freq_character/include/count_freq_character_header.hpp
  tasks/seq/budazhapova_e_count_freq_character/pref_tests/count_freq_charactes_pref_tests.cpp
  tasks/seq/budazhapova_e_count_freq_character/src/count_freq_character.cpp
Labels: approved - Alexander, on review - Arseniy

#311 Fix Revert "Кондратьев Ярослав. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы"
  tasks/mpi/kondratev_ya_max_col_matrix/func_tests/main.cpp
  tasks/mpi/kondratev_ya_max_col_matrix/include/ops_mpi.hpp
  tasks/mpi/kondratev_ya_max_col_matrix/perf_tests/main.cpp
  tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
  tasks/seq/kondratev_ya_max_col_matrix/func_tests/main.cpp
  tasks/seq/kondratev_ya_max_col_matrix/include/ops_seq.hpp
  tasks/seq/kondratev_ya_max_col_matrix/perf_tests/main.cpp
  tasks/seq/kondratev_ya_max_col_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#282 Зиновьев Александр Задача 1 Вариант 12 Сумма значений по столбцам матрицы
  tasks/mpi/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
  tasks/mpi/zinoviev_a_sum_cols_matrix/include/ops_mpi.hpp
  tasks/mpi/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
  tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
  tasks/mpi/zinoviev_readers_and_writers/func_tests/main.cpp
  tasks/mpi/zinoviev_readers_and_writers/include/ops_mpi.hpp
  tasks/mpi/zinoviev_readers_and_writers/perf_tests/main.cpp
  tasks/mpi/zinoviev_readers_and_writers/src/ops_mpi.cpp
  tasks/seq/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
  tasks/seq/zinoviev_a_sum_cols_matrix/include/ops_seq.hpp
  tasks/seq/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
  tasks/seq/zinoviev_a_sum_cols_matrix/src/ops_seq.cpp
  tasks/seq/zinoviev_readers_and_writers/func_tests/main.cpp
  tasks/seq/zinoviev_readers_and_writers/include/ops_seq.hpp
  tasks/seq/zinoviev_readers_and_writers/perf_tests/main.cpp
  tasks/seq/zinoviev_readers_and_writers/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#285 Чистов Алексей.Задача 2.Вариант 9. Обобщенная передача от всех одному(gather).
  tasks/mpi/chistov_a_gather_boost/func_tests/gather_boost.cpp
  tasks/mpi/chistov_a_gather_boost/func_tests/sort_boost.cpp
  tasks/mpi/chistov_a_gather_boost/include/gather_boost.hpp
  tasks/mpi/chistov_a_gather_boost/include/sort_boost.hpp
  tasks/mpi/chistov_a_gather_boost/perf_tests/gather_boost.cpp
  tasks/mpi/chistov_a_gather_boost/perf_tests/sort_boost.cpp
  tasks/mpi/chistov_a_gather_boost/src/gather_boost.cpp
  tasks/mpi/chistov_a_gather_boost/src/sort_boost.cpp
  tasks/mpi/chistov_a_gather_my/func_tests/gather_my.cpp
  tasks/mpi/chistov_a_gather_my/func_tests/sort_my.cpp
  tasks/mpi/chistov_a_gather_my/include/gather_my.hpp
  tasks/mpi/chistov_a_gather_my/include/sort_my.hpp
  tasks/mpi/chistov_a_gather_my/perf_tests/gather_my.cpp
  tasks/mpi/chistov_a_gather_my/perf_tests/sort_my.cpp
  tasks/mpi/chistov_a_gather_my/src/gather_my.cpp
  tasks/mpi/chistov_a_gather_my/src/sort_my.cpp
Labels: approved - Alexander, approved - Arseniy

#299 Грудзин Константин. Задача 2. Вариант 7. Реализация allreduce
  tasks/mpi/grudzin_k_all_reduce_boost/func_tests/main.cpp
  tasks/mpi/grudzin_k_all_reduce_boost/include/ops_mpi.hpp
  tasks/mpi/grudzin_k_all_reduce_boost/perf_tests/main.cpp
  tasks/mpi/grudzin_k_all_reduce_boost/src/ops_mpi.cpp
  tasks/mpi/grudzin_k_all_reduce_student/func_tests/main.cpp
  tasks/mpi/grudzin_k_all_reduce_student/include/ops_mpi.hpp
  tasks/mpi/grudzin_k_all_reduce_student/perf_tests/main.cpp
  tasks/mpi/grudzin_k_all_reduce_student/src/ops_mpi.cpp
  tasks/seq/dormidontov_e_min_value_by_columns_seq/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#302 Соловьев Данила. Задача 2. Вариант 14. Топология сети "Гиперкуб"
  tasks/mpi/solovyev_d_topology_hypercube/func_tests/main.cpp
  tasks/mpi/solovyev_d_topology_hypercube/include/header.hpp
  tasks/mpi/solovyev_d_topology_hypercube/perf_tests/main.cpp
  tasks/mpi/solovyev_d_topology_hypercube/src/source.cpp
Labels: approved - Alexander, approved - Arseniy

#298 Миронов Арсений. Задача 2. Вариант 5. Передача от одного всем (broadcast).
  tasks/mpi/mironov_a_broadcast/func_tests/main.cpp
  tasks/mpi/mironov_a_broadcast/include/ops_mpi.hpp
  tasks/mpi/mironov_a_broadcast/perf_tests/main.cpp
  tasks/mpi/mironov_a_broadcast/src/ops_mpi.cpp
  tasks/mpi/mironov_a_broadcast_custom/func_tests/main.cpp
  tasks/mpi/mironov_a_broadcast_custom/include/ops_mpi.hpp
  tasks/mpi/mironov_a_broadcast_custom/perf_tests/main.cpp
  tasks/mpi/mironov_a_broadcast_custom/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#312 Гнитиенко Кирилл. Задача 2. Вариант 27. Повышение контраста изображения
  tasks/mpi/gnitienko_k_contrast_enhancement/func_tests/main.cpp
  tasks/mpi/gnitienko_k_contrast_enhancement/include/ops_mpi.hpp
  tasks/mpi/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
  tasks/mpi/gnitienko_k_contrast_enhancement/src/ops_mpi.cpp
  tasks/seq/gnitienko_k_contrast_enhancement/func_tests/main.cpp
  tasks/seq/gnitienko_k_contrast_enhancement/include/ops_seq.hpp
  tasks/seq/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
  tasks/seq/gnitienko_k_contrast_enhancement/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#313 Куракин Матвей. Задача 2. Вариант 1. Производители-потребители
  tasks/mpi/kurakin_m_producer_consumer/func_tests/kurakin_producer_consumer.cpp
  tasks/mpi/kurakin_m_producer_consumer/include/kurakin_producer_consumer_ops_mpi.hpp
  tasks/mpi/kurakin_m_producer_consumer/perf_tests/kurakin_producer_consumer.cpp
  tasks/mpi/kurakin_m_producer_consumer/src/kurakin_producer_consumer_ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#318 Шурыгин Сергей. Задача №2. Вариант №16. Ленточная вертикальная схема
  tasks/mpi/shurigin_s_vertikal_shema_mpi/func_tests/main.cpp
  tasks/mpi/shurigin_s_vertikal_shema_mpi/include/ops_mpi.hpp
  tasks/mpi/shurigin_s_vertikal_shema_mpi/perf_tests/main.cpp
  tasks/mpi/shurigin_s_vertikal_shema_mpi/src/ops_mpi.cpp
  tasks/seq/shurigin_s_vertikal_shema/func_tests/main.cpp
  tasks/seq/shurigin_s_vertikal_shema/include/ops_seq.hpp
  tasks/seq/shurigin_s_vertikal_shema/perf_tests/main.cpp
  tasks/seq/shurigin_s_vertikal_shema/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#321 Моисеев Артём. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А
  tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/func_tests/main.cpp
  tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/include/ops_mpi.hpp
  tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/perf_tests/main.cpp
  tasks/mpi/moiseev_a_ribbon_hor_scheme_splt_mat_a/src/ops_mpi.cpp
  tasks/seq/moiseev_a_ribbon_hor_scheme_splt_mat_a/func_tests/main.cpp
  tasks/seq/moiseev_a_ribbon_hor_scheme_splt_mat_a/include/ops_seq.hpp
  tasks/seq/moiseev_a_ribbon_hor_scheme_splt_mat_a/perf_tests/main.cpp
  tasks/seq/moiseev_a_ribbon_hor_scheme_splt_mat_a/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#323 Дрождинов Дмитрий. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/include/ops_seq.hpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#332 Сорокин Андрей. Задача 2. Вариант 1. Производители-потребители
  tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
  tasks/mpi/sorokin_a_producer_consumer/include/ops_mpi.hpp
  tasks/mpi/sorokin_a_producer_consumer/perf_tests/main.cpp
  tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#336 Гусев Никита. Задача 2. Вариант 14. Топология сети передачи данных - гиперкуб
  tasks/mpi/gusev_n_hypercube_topology/func_tests/main.cpp
  tasks/mpi/gusev_n_hypercube_topology/include/ops_mpi.hpp
  tasks/mpi/gusev_n_hypercube_topology/perf_tests/main.cpp
  tasks/mpi/gusev_n_hypercube_topology/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#337 Смирнов Илья. Задача 2. Вариант 17. Ленточная горизонатльная схема - разбиение только матрицы А.
  tasks/mpi/smirnov_i_tape_splitting_A/func_tests/main.cpp
  tasks/mpi/smirnov_i_tape_splitting_A/include/ops_mpi.hpp
  tasks/mpi/smirnov_i_tape_splitting_A/perf_tests/main.cpp
  tasks/mpi/smirnov_i_tape_splitting_A/src/ops_mpi.cpp
  tasks/seq/smirnov_i_tape_splitting_A/func_tests/main.cpp
  tasks/seq/smirnov_i_tape_splitting_A/include/ops_seq.hpp
  tasks/seq/smirnov_i_tape_splitting_A/perf_tests/main.cpp
  tasks/seq/smirnov_i_tape_splitting_A/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#331 Малышев Антон. Задача 2. Вариант 24. Метод простой итерации.
  tasks/mpi/malyshev_a_simple_iteration_method/func_tests/main.cpp
  tasks/mpi/malyshev_a_simple_iteration_method/include/matrix.hpp
  tasks/mpi/malyshev_a_simple_iteration_method/include/ops_mpi.hpp
  tasks/mpi/malyshev_a_simple_iteration_method/perf_tests/main.cpp
  tasks/mpi/malyshev_a_simple_iteration_method/src/matrix.cpp
  tasks/mpi/malyshev_a_simple_iteration_method/src/ops_mpi.cpp
  tasks/seq/malyshev_a_simple_iteration_method/func_tests/main.cpp
  tasks/seq/malyshev_a_simple_iteration_method/include/matrix.hpp
  tasks/seq/malyshev_a_simple_iteration_method/include/ops_seq.hpp
  tasks/seq/malyshev_a_simple_iteration_method/perf_tests/main.cpp
  tasks/seq/malyshev_a_simple_iteration_method/src/matrix.cpp
  tasks/seq/malyshev_a_simple_iteration_method/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#338 Милованкин Максим. Задача 2. Вариант 14. Топология Гиперкуб.
  tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
  tasks/mpi/milovankin_m_hypercube_topology/include/ops_mpi.hpp
  tasks/mpi/milovankin_m_hypercube_topology/perf_tests/main.cpp
  tasks/mpi/milovankin_m_hypercube_topology/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#340 Ведерникова Ксения. Задача 2. Вариант 12. Топология сети "Звезда".
  tasks/mpi/vedernikova_k_star_topology_mpi/func_tests/main.cpp
  tasks/mpi/vedernikova_k_star_topology_mpi/include/ops_mpi.hpp
  tasks/mpi/vedernikova_k_star_topology_mpi/perf_tests/main.cpp
  tasks/mpi/vedernikova_k_star_topology_mpi/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#344 Береснев Антон. Задача 2. Вариант 27. Повышение контраста
  tasks/mpi/beresnev_a_increase_contrast/func_tests/main.cpp
  tasks/mpi/beresnev_a_increase_contrast/include/ops_mpi.hpp
  tasks/mpi/beresnev_a_increase_contrast/perf_tests/main.cpp
  tasks/mpi/beresnev_a_increase_contrast/src/ops_mpi.cpp
  tasks/seq/beresnev_a_increase_contrast/ans.ppm
  tasks/seq/beresnev_a_increase_contrast/ans1.ppm
  tasks/seq/beresnev_a_increase_contrast/func_tests/main.cpp
  tasks/seq/beresnev_a_increase_contrast/include/ops_seq.hpp
  tasks/seq/beresnev_a_increase_contrast/input.ppm
  tasks/seq/beresnev_a_increase_contrast/input1.ppm
  tasks/seq/beresnev_a_increase_contrast/perf_tests/main.cpp
  tasks/seq/beresnev_a_increase_contrast/src/ops_seq.cpp
Labels: approved - Alexander

#345 Кошкин Никита. Задача 2. Вариант 2. Читатели-Писатели.
  tasks/mpi/koshkin_n_readers_writers/func_tests/main.cpp
  tasks/mpi/koshkin_n_readers_writers/include/ops_mpi.hpp
  tasks/mpi/koshkin_n_readers_writers/perf_tests/main.cpp
  tasks/mpi/koshkin_n_readers_writers/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#347 Кудряшова Ирина. Задача 2. Вариант 9. Обобщенная передача от всех одному (gather)
  tasks/mpi/kudryashova_i_gather my/func_tests/GatherMyMPIFuncTests.cpp
  tasks/mpi/kudryashova_i_gather my/include/GatherMyMPI.hpp
  tasks/mpi/kudryashova_i_gather my/perf_tests/GatherMyMPIPerfTests.cpp
  tasks/mpi/kudryashova_i_gather my/src/GatherMyMPI.cpp
  tasks/mpi/kudryashova_i_gather/func_tests/GatherMPIFuncTests.cpp
  tasks/mpi/kudryashova_i_gather/include/GatherMPI.hpp
  tasks/mpi/kudryashova_i_gather/perf_tests/GatherMPIPerfTests.cpp
  tasks/mpi/kudryashova_i_gather/src/GatherMPI.cpp
Labels: approved - Alexander, approved - Arseniy

#308 Морозов Егор. Задача 2. Вариант 2. Задача «Читатели-Писатели»
  tasks/mpi/morozov_e_writers_readers/func_tests/main.cpp
  tasks/mpi/morozov_e_writers_readers/include/ops_mpi.hpp
  tasks/mpi/morozov_e_writers_readers/perf_tests/main.cpp
  tasks/mpi/morozov_e_writers_readers/src/ops_mpi.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#327 Соловьев Алексей. Задача 2. Вариант 12. Топология сети Звезда.
  tasks/mpi/solovev_a_star_topology/func_tests/main.cpp
  tasks/mpi/solovev_a_star_topology/include/ops_mpi.hpp
  tasks/mpi/solovev_a_star_topology/perf_tests/main.cpp
  tasks/mpi/solovev_a_star_topology/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#377 Алпутов Иван. Задача 2. Вариант 14. Топология сетей передачи данных "Гиперкуб"
  tasks/mpi/alputov_i_topology_hypercube/func_tests/main.cpp
  tasks/mpi/alputov_i_topology_hypercube/include/ops_mpi.hpp
  tasks/mpi/alputov_i_topology_hypercube/perf_tests/main.cpp
  tasks/mpi/alputov_i_topology_hypercube/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#343 Коротин Егор. Задача 2. Вариант 8. Реализация Scatter
  tasks/mpi/korotin_e_my_scatter/func_tests/main.cpp
  tasks/mpi/korotin_e_my_scatter/include/ops_mpi.hpp
  tasks/mpi/korotin_e_my_scatter/perf_tests/main.cpp
  tasks/mpi/korotin_e_my_scatter/src/ops_mpi.cpp
  tasks/mpi/korotin_e_scatter/func_tests/main.cpp
  tasks/mpi/korotin_e_scatter/include/ops_mpi.hpp
  tasks/mpi/korotin_e_scatter/perf_tests/main.cpp
  tasks/mpi/korotin_e_scatter/src/ops_mpi.cpp
Labels: on review - Alexander, approved - Arseniy

#353 Волочаев Серафим Задача 2. Вариант 16: Ленточная вертикальная схема
  tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/func_tests/main.cpp
  tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/include/ops_mpi.hpp
  tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/perf_tests/main.cpp
  tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/src/ops_mpi.cpp
  tasks/seq/volochaev_s_vertical_ribbon_scheme_16/func_tests/main.cpp
  tasks/seq/volochaev_s_vertical_ribbon_scheme_16/include/ops_seq.hpp
  tasks/seq/volochaev_s_vertical_ribbon_scheme_16/perf_tests/main.cpp
  tasks/seq/volochaev_s_vertical_ribbon_scheme_16/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#356 Сарафанов Максим. Задача 2 вариант 21 Метод Гаусса-Жордана
  tasks/mpi/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
  tasks/mpi/sarafanov_m_gauss_jordan_method/include/ops_mpi.hpp
  tasks/mpi/sarafanov_m_gauss_jordan_method/perf_tests/main.cpp
  tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
  tasks/seq/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
  tasks/seq/sarafanov_m_gauss_jordan_method/include/ops_seq.hpp
  tasks/seq/sarafanov_m_gauss_jordan_method/perf_tests/main.cpp
  tasks/seq/sarafanov_m_gauss_jordan_method/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#398 Комшина Дарья. Задача 2. Вариант 13. Топология сети передачи данных решетка-тор.
  tasks/mpi/komshina_d_grid_torus_topology/func_tests/main.cpp
  tasks/mpi/komshina_d_grid_torus_topology/include/ops_mpi.hpp
  tasks/mpi/komshina_d_grid_torus_topology/perf_tests/main.cpp
  tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#400 Лопатин Илья. Задача 2. Вариант 15. Ленточная горизонтальная схема.
  tasks/mpi/lopatin_i_strip_horizontal_scheme/func_tests/stripHorizontalSchemeFuncTestsMPI.cpp
  tasks/mpi/lopatin_i_strip_horizontal_scheme/include/stripHorizontalSchemeHeaderMPI.hpp
  tasks/mpi/lopatin_i_strip_horizontal_scheme/perf_tests/stripHorizontalSchemePerfTestsMPI.cpp
  tasks/mpi/lopatin_i_strip_horizontal_scheme/src/stripHorizontalSchemeMPI.cpp
  tasks/seq/lopatin_i_strip_horizontal_scheme/func_tests/stripHorizontalSchemeFuncTestsSeq.cpp
  tasks/seq/lopatin_i_strip_horizontal_scheme/include/stripHorizontalSchemeHeaderSeq.hpp
  tasks/seq/lopatin_i_strip_horizontal_scheme/perf_tests/stripHorizontalSchemePerfTestsSeq.cpp
  tasks/seq/lopatin_i_strip_horizontal_scheme/src/stripHorizontalSchemeSeq.cpp
Labels: approved - Alexander, approved - Arseniy

#395 Хованский Дмитрий. Задача 2. Вариант 16. Ленточная вертикальная схема.
  tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
  tasks/mpi/khovansky_d_ribbon_vertical_scheme/include/ops_mpi.hpp
  tasks/mpi/khovansky_d_ribbon_vertical_scheme/perf_tests/main.cpp
  tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
  tasks/seq/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
  tasks/seq/khovansky_d_ribbon_vertical_scheme/include/ops_seq.hpp
  tasks/seq/khovansky_d_ribbon_vertical_scheme/perf_tests/main.cpp
  tasks/seq/khovansky_d_ribbon_vertical_scheme/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#401 Резанцева Анастасия. Задача 2. Вариант 24. Метод простых итераций.
  tasks/mpi/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
  tasks/mpi/rezantseva_a_simple_iteration_method/include/ops_mpi_rezantseva.hpp
  tasks/mpi/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
  tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
  tasks/seq/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
  tasks/seq/rezantseva_a_simple_iteration_method/include/ops_seq_rezantseva.hpp
  tasks/seq/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
  tasks/seq/rezantseva_a_simple_iteration_method/src/ops_seq_rezantseva.cpp
Labels: approved - Alexander, approved - Arseniy

#328 Мухина Маргарита. Задача 2. Вариант 15. Ленточная горизонтальная схема
  tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
  tasks/mpi/muhina_m_horizontal_cheme/include/ops_mpi.hpp
  tasks/mpi/muhina_m_horizontal_cheme/perf_tests/main.cpp
  tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
  tasks/seq/muhina_m_horizontal_cheme/func_tests/main.cpp
  tasks/seq/muhina_m_horizontal_cheme/include/ops_seq.hpp
  tasks/seq/muhina_m_horizontal_cheme/perf_tests/main.cpp
  tasks/seq/muhina_m_horizontal_cheme/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#307 Васильев Сергей Задача 3 вариант 28 Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.
  tasks/mpi/vasilev_s_gaus3x3/func_tests/main.cpp
  tasks/mpi/vasilev_s_gaus3x3/include/ops_mpi.hpp
  tasks/mpi/vasilev_s_gaus3x3/perf_tests/main.cpp
  tasks/mpi/vasilev_s_gaus3x3/src/ops_mpi.cpp
  tasks/seq/vasilev_s_gaus3x3/func_tests/main.cpp
  tasks/seq/vasilev_s_gaus3x3/include/ops_seq.hpp
  tasks/seq/vasilev_s_gaus3x3/perf_tests/main.cpp
  tasks/seq/vasilev_s_gaus3x3/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#351 Шульпин Илья. Задача 2. Вариант 18. Умножение матриц, ленточная горизонтальная схема А, вертикальное В
  tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
  tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
  tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
  tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
  tasks/seq/shulpin_i_strip_hA_vB/func_tests/main.cpp
  tasks/seq/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
  tasks/seq/shulpin_i_strip_hA_vB/perf_tests/main.cpp
  tasks/seq/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
Labels: approved - Alexander, approved - Arseniy

#335 Титов Семён. Задача 2. Вариант 24. Метод простых итераций
  tasks/mpi/titov_s_simple_iteration/func_tests/main.cpp
  tasks/mpi/titov_s_simple_iteration/include/ops_mpi.hpp
  tasks/mpi/titov_s_simple_iteration/perf_tests/main.cpp
  tasks/mpi/titov_s_simple_iteration/src/ops_mpi.cpp
  tasks/seq/titov_s_simple_iteration/func_tests/main.cpp
  tasks/seq/titov_s_simple_iteration/include/ops_seq.hpp
  tasks/seq/titov_s_simple_iteration/perf_tests/main.cpp
  tasks/seq/titov_s_simple_iteration/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#357 Соцков Андрей. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/include/ops_mpi.hpp
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/perf_tests/main.cpp
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/include/ops_seq.hpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/perf_tests/main.cpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#365 Харин Матвей. Задача 2. Вариант 23. Итеративные методы (Зейделя)
  tasks/mpi/kharin_m_seidel_method/func_tests/main.cpp
  tasks/mpi/kharin_m_seidel_method/include/ops_mpi.hpp
  tasks/mpi/kharin_m_seidel_method/perf_tests/main.cpp
  tasks/mpi/kharin_m_seidel_method/src/ops_mpi.cpp
  tasks/seq/kharin_m_seidel_method/func_tests/main.cpp
  tasks/seq/kharin_m_seidel_method/include/ops_seq.hpp
  tasks/seq/kharin_m_seidel_method/perf_tests/main.cpp
  tasks/seq/kharin_m_seidel_method/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#366 Отурин Александр. Задача 2. Вариант 26. Сглаживание изображений.
  tasks/mpi/oturin_a_image_smoothing/circle.bmp
  tasks/mpi/oturin_a_image_smoothing/color.bmp
  tasks/mpi/oturin_a_image_smoothing/func_tests/main.cpp
  tasks/mpi/oturin_a_image_smoothing/include/ops_mpi.hpp
  tasks/mpi/oturin_a_image_smoothing/line.bmp
  tasks/mpi/oturin_a_image_smoothing/perf_tests/main.cpp
  tasks/mpi/oturin_a_image_smoothing/src/ops_mpi.cpp
  tasks/seq/oturin_a_image_smoothing/circle.bmp
  tasks/seq/oturin_a_image_smoothing/circleREF.bmp
  tasks/seq/oturin_a_image_smoothing/color.bmp
  tasks/seq/oturin_a_image_smoothing/colorREF.bmp
  tasks/seq/oturin_a_image_smoothing/func_tests/main.cpp
  tasks/seq/oturin_a_image_smoothing/include/ops_seq.hpp
  tasks/seq/oturin_a_image_smoothing/line.bmp
  tasks/seq/oturin_a_image_smoothing/lineREF.bmp
  tasks/seq/oturin_a_image_smoothing/perf_tests/main.cpp
  tasks/seq/oturin_a_image_smoothing/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#370 Зайцев Артем. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter).
  tasks/mpi/zaitsev_a_scatter_handwritten/func_tests/main.cpp
  tasks/mpi/zaitsev_a_scatter_handwritten/include/ops_mpi.hpp
  tasks/mpi/zaitsev_a_scatter_handwritten/perf_tests/main.cpp
  tasks/mpi/zaitsev_a_scatter_handwritten/src/ops_mpi.cpp
  tasks/mpi/zaitsev_a_scatter_mpi/func_tests/main.cpp
  tasks/mpi/zaitsev_a_scatter_mpi/include/ops_mpi.hpp
  tasks/mpi/zaitsev_a_scatter_mpi/perf_tests/main.cpp
  tasks/mpi/zaitsev_a_scatter_mpi/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#372 Холин Кирилл. Задача 2. Вариант 23. Итеративные методы (Зейделя).
  tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
  tasks/mpi/kholin_k_iterative_methods_Seidel/include/ops_mpi.hpp
  tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
  tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
  tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
  tasks/seq/kholin_k_iterative_methods_Seidel/include/ops_seq.hpp
  tasks/seq/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
  tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#373 Ковалев Константин. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки)
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/include/header.hpp
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/perf_tests/main.cpp
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/src/sourse.cpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/include/header.hpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/perf_tests/main.cpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/src/sourse.cpp
Labels: approved - Alexander, approved - Arseniy

#376 Бессонов Егор. Задача 2. Вариант 12. Топология сетей передачи данных - Звезда
  tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
  tasks/mpi/bessonov_e_star_topology/include/ops_mpi.hpp
  tasks/mpi/bessonov_e_star_topology/perf_tests/main.cpp
  tasks/mpi/bessonov_e_star_topology/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#361 Борисов Сергей. Задача 2. Вариант 5. Передача от одного всем (broadcast)
  tasks/mpi/borisov_s_broadcast/func_tests/main.cpp
  tasks/mpi/borisov_s_broadcast/include/ops_mpi.hpp
  tasks/mpi/borisov_s_broadcast/perf_tests/main.cpp
  tasks/mpi/borisov_s_broadcast/src/ops_mpi.cpp
  tasks/mpi/borisov_s_my_broadcast/func_tests/main.cpp
  tasks/mpi/borisov_s_my_broadcast/include/ops_mpi.hpp
  tasks/mpi/borisov_s_my_broadcast/perf_tests/main.cpp
  tasks/mpi/borisov_s_my_broadcast/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#407 Ворошилов Виталий. Задача 2. Вариант 13. Топология сетей передачи данных "Решётка-тор"
  tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
  tasks/mpi/voroshilov_v_torus_grid/include/ops_mpi.hpp
  tasks/mpi/voroshilov_v_torus_grid/perf_tests/main.cpp
  tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#429 Лаганина Елена. Задача 2. Вариант 2. Читатели-писатели.
  tasks/mpi/laganina_e_readers_writers/func_tests/main.cpp
  tasks/mpi/laganina_e_readers_writers/include/ops_mpi.hpp
  tasks/mpi/laganina_e_readers_writers/perf_tests/main.cpp
  tasks/mpi/laganina_e_readers_writers/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#432 Лысов Иван. Задача 2. Вариант 24. Метод простой итерации.
  tasks/mpi/lysov_i_simple_iteration_method/func_tests/main.cpp
  tasks/mpi/lysov_i_simple_iteration_method/include/ops_mpi.hpp
  tasks/mpi/lysov_i_simple_iteration_method/perf_tests/main.cpp
  tasks/mpi/lysov_i_simple_iteration_method/src/ops_mpi.cpp
  tasks/seq/lysov_i_simple_iteration_method/func_tests/main.cpp
  tasks/seq/lysov_i_simple_iteration_method/include/ops_seq.hpp
  tasks/seq/lysov_i_simple_iteration_method/perf_tests/main.cpp
  tasks/seq/lysov_i_simple_iteration_method/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#380 Петров Олег. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема
  tasks/mpi/petrov_o_horizontal_gauss_method/func_tests/main.cpp
  tasks/mpi/petrov_o_horizontal_gauss_method/include/ops_mpi.hpp
  tasks/mpi/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
  tasks/mpi/petrov_o_horizontal_gauss_method/src/ops_mpi.cpp
  tasks/seq/petrov_o_horizontal_gauss_method/func_tests/main.cpp
  tasks/seq/petrov_o_horizontal_gauss_method/include/ops_seq.hpp
  tasks/seq/petrov_o_horizontal_gauss_method/perf_tests/main.cpp
  tasks/seq/petrov_o_horizontal_gauss_method/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#382 Сидорина Полина. Задача 2. Вариант 5. Передача от одного всем (broadcast).
  tasks/mpi/sidorina_p_broadcast/func_tests/main.cpp
  tasks/mpi/sidorina_p_broadcast/include/ops_mpi.hpp
  tasks/mpi/sidorina_p_broadcast/perf_tests/main.cpp
  tasks/mpi/sidorina_p_broadcast/src/ops_mpi.cpp
  tasks/mpi/sidorina_p_broadcast_m/func_tests/main.cpp
  tasks/mpi/sidorina_p_broadcast_m/include/ops_mpi.hpp
  tasks/mpi/sidorina_p_broadcast_m/perf_tests/main.cpp
  tasks/mpi/sidorina_p_broadcast_m/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#397 Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_mpi.hpp
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_seq.hpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#424 Дормидонтов Егор.Задача 2.Вариант 11.Топология кольцо
  tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
  tasks/mpi/dormidontov_e_circle_topology/include/dect_ops_mpi.hpp
  tasks/mpi/dormidontov_e_circle_topology/perf_tests/dect_main.cpp
  tasks/mpi/dormidontov_e_circle_topology/src/dect_ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#381 Одинцов Михаил. Задача 2 Вариант 16 Ленточная вертикальная схема.
  tasks/mpi/Odintsov_M_VerticalRibbon_mpi/func_tests/main.cpp
  tasks/mpi/Odintsov_M_VerticalRibbon_mpi/include/ops_mpi.hpp
  tasks/mpi/Odintsov_M_VerticalRibbon_mpi/perf_tests/main.cpp
  tasks/mpi/Odintsov_M_VerticalRibbon_mpi/src/ops_mpi.cpp
  tasks/seq/Odintsov_M_VerticalRibbon_seq/func_tests/main.cpp
  tasks/seq/Odintsov_M_VerticalRibbon_seq/include/ops_seq.hpp
  tasks/seq/Odintsov_M_VerticalRibbon_seq/perf_tests/main.cpp
  tasks/seq/Odintsov_M_VerticalRibbon_seq/src/ops_seq.cpp
Labels: wait ci, approved - Alexander, approved - Arseniy

#350 Пикарычев Илья. Задача 2. Вариант 4. Задача "Спящий брадобрей"
  tasks/mpi/pikarychev_i_sleeping_barber/func_tests/main.cpp
  tasks/mpi/pikarychev_i_sleeping_barber/include/ops_mpi.hpp
  tasks/mpi/pikarychev_i_sleeping_barber/perf_tests/main.cpp
  tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
Labels: approved - Alexander, on review - Arseniy, requires > 4 reviews

#379 Тюрин Михаил. Задача 2. Вариант 10. Топологии сетей передачи данных "Линейка".
  tasks/mpi/tyurin_m_linear_topology/func_tests/main.cpp
  tasks/mpi/tyurin_m_linear_topology/include/ops_mpi.hpp
  tasks/mpi/tyurin_m_linear_topology/perf_tests/main.cpp
  tasks/mpi/tyurin_m_linear_topology/src/ops_mpi.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy, requires > 4 reviews

#402 Филатьев Владислав. Задача 2. Вариант 23. Итеративные методы (Зейделя)
  tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
  tasks/mpi/filatev_v_metod_zedela/include/ops_mpi.hpp
  tasks/mpi/filatev_v_metod_zedela/perf_tests/main.cpp
  tasks/mpi/filatev_v_metod_zedela/src/ops_mpi.cpp
  tasks/seq/filatev_v_metod_zedela/func_tests/main.cpp
  tasks/seq/filatev_v_metod_zedela/include/ops_seq.hpp
  tasks/seq/filatev_v_metod_zedela/perf_tests/main.cpp
  tasks/seq/filatev_v_metod_zedela/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#433 Вершинина Александра. Задача 2. Вариант 26. Сглаживание изображения
  tasks/mpi/vershinina_a_image_smoothing/func_tests/main.cpp
  tasks/mpi/vershinina_a_image_smoothing/include/ops_mpi.hpp
  tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
  tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
  tasks/seq/vershinina_a_image_smoothing/func_tests/main.cpp
  tasks/seq/vershinina_a_image_smoothing/include/ops_seq.hpp
  tasks/seq/vershinina_a_image_smoothing/perf_tests/main.cpp
  tasks/seq/vershinina_a_image_smoothing/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#403 Кошкин Матвей. Задача 2. Вариант 3. Задача «Обедающие философы».
  tasks/mpi/koshkin_m_dining_philosophers/func_tests/main.cpp
  tasks/mpi/koshkin_m_dining_philosophers/include/ops_mpi.hpp
  tasks/mpi/koshkin_m_dining_philosophers/perf_tests/main.cpp
  tasks/mpi/koshkin_m_dining_philosophers/src/ops_mpi.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy, requires > 4 reviews

#384 Садиков Иван. Задача 2. Вариант 9. Обобщенная передача от всех одному (gather)
  tasks/mpi/sadikov_I_gather/func_tests/main.cpp
  tasks/mpi/sadikov_I_gather/include/ops_mpi.h
  tasks/mpi/sadikov_I_gather/perf_tests/main.cpp
  tasks/mpi/sadikov_I_gather/src/mpi_src.cpp
  tasks/seq/sadikov_I_gather/func_tests/seq_func_tests.cpp
  tasks/seq/sadikov_I_gather/include/sq_task.h
  tasks/seq/sadikov_I_gather/perf_tests/main.cpp
  tasks/seq/sadikov_I_gather/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#325 Колодкин Григорий. Задача 2. Вариант 27. Повышение контрастности изображения.
  tasks/mpi/kolodkin_g_image_contrast/func_tests/main.cpp
  tasks/mpi/kolodkin_g_image_contrast/include/ops_mpi.hpp
  tasks/mpi/kolodkin_g_image_contrast/perf_tests/main.cpp
  tasks/mpi/kolodkin_g_image_contrast/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#418 FIX Баранов Алексей. Задача 2. Вариант 11. Топология сети кольцо
  tasks/mpi/baranov_a_ring_topology/perf_tests/main_topology.cpp
  tasks/mpi/baranov_a_ring_topology/src/source_topology.cpp
Labels: approved - Alexander, approved - Arseniy

#394 Межуев Максим Задача 2 Вариант 13. Решетка-Тор
  tasks/mpi/mezhuev_m_lattice_torus/func_tests/main.cpp
  tasks/mpi/mezhuev_m_lattice_torus/include/mpi.hpp
  tasks/mpi/mezhuev_m_lattice_torus/perf_tests/main.cpp
  tasks/mpi/mezhuev_m_lattice_torus/src/mpi.cpp
Labels: approved - Alexander, on review - Arseniy, requires > 4 reviews

#396 Golovkin Maksim. Task№2. Var №17. Rowwise_matrix_partitioning
  tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
  tasks/mpi/golovkin_integration_rectangular_method/include/ops_mpi.hpp
  tasks/mpi/golovkin_integration_rectangular_method/perf_tests/main.cpp
  tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
  tasks/mpi/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
  tasks/mpi/golovkin_rowwise_matrix_partitioning/include/ops_mpi.hpp
  tasks/mpi/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
  tasks/mpi/golovkin_rowwise_matrix_partitioning/src/ops_mpi.cpp
  tasks/seq/golovkin_integration_rectangular_method/func_tests/main.cpp
  tasks/seq/golovkin_integration_rectangular_method/include/ops_seq.hpp
  tasks/seq/golovkin_integration_rectangular_method/perf_tests/main.cpp
  tasks/seq/golovkin_integration_rectangular_method/src/ops_seq.cpp
  tasks/seq/golovkin_rowwise_matrix_partitioning/func_tests/main.cpp
  tasks/seq/golovkin_rowwise_matrix_partitioning/include/ops_seq.hpp
  tasks/seq/golovkin_rowwise_matrix_partitioning/perf_tests/main.cpp
  tasks/seq/golovkin_rowwise_matrix_partitioning/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#412 Плеханов Даниил. Задача 2. Вариант 7. Реализация all_reduce.
  tasks/mpi/plekhanov_d_allreduce_boost/func_tests/main.cpp
  tasks/mpi/plekhanov_d_allreduce_boost/include/ops_mpi.hpp
  tasks/mpi/plekhanov_d_allreduce_boost/perf_tests/main.cpp
  tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
  tasks/mpi/plekhanov_d_allreduce_mine/func_tests/main.cpp
  tasks/mpi/plekhanov_d_allreduce_mine/include/ops_mpi.hpp
  tasks/mpi/plekhanov_d_allreduce_mine/perf_tests/main.cpp
  tasks/mpi/plekhanov_d_allreduce_mine/src/ops_mpi.cpp
Labels: on review - Alexander, approved - Arseniy

#404 Лаврентьев Алексей. Задача 2. Вариант 10. Топологии сетей передачи данных "Линейка".
  tasks/mpi/lavrentyev_a_line_topology/func_tests/main.cpp
  tasks/mpi/lavrentyev_a_line_topology/include/ops_mpi.hpp
  tasks/mpi/lavrentyev_a_line_topology/perf_tests/main.cpp
  tasks/mpi/lavrentyev_a_line_topology/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#334 Куракин Матвей. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема
  tasks/mpi/kurakin_m_graham_scan/func_tests/kurakin_graham_scan.cpp
  tasks/mpi/kurakin_m_graham_scan/include/kurakin_graham_scan_ops_mpi.hpp
  tasks/mpi/kurakin_m_graham_scan/perf_tests/kurakin_graham_scan.cpp
  tasks/mpi/kurakin_m_graham_scan/src/kurakin_graham_scan_ops_mpi.cpp
  tasks/seq/kurakin_m_graham_scan/func_tests/kurakin_graham_scan.cpp
  tasks/seq/kurakin_m_graham_scan/include/kurakin_graham_scan_ops_seq.hpp
  tasks/seq/kurakin_m_graham_scan/perf_tests/kurakin_graham_scan.cpp
  tasks/seq/kurakin_m_graham_scan/src/kurakin_graham_scan_ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#390 Филатьева Елизавета. Задача 2. Вариант 19. Метод Гаусса — ленточная горизонтальная схема
  tasks/mpi/filateva_e_metod_gausa/func_tests/main.cpp
  tasks/mpi/filateva_e_metod_gausa/include/ops_mpi.hpp
  tasks/mpi/filateva_e_metod_gausa/perf_tests/main.cpp
  tasks/mpi/filateva_e_metod_gausa/src/ops_mpi.cpp
  tasks/seq/filateva_e_metod_gausa/func_tests/main.cpp
  tasks/seq/filateva_e_metod_gausa/include/ops_seq.hpp
  tasks/seq/filateva_e_metod_gausa/perf_tests/main.cpp
  tasks/seq/filateva_e_metod_gausa/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy, requires > 4 reviews

#314 Куракин Матвей. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/kurakin_min_rows_matrix.cpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/include/kurakin_min_rows_matrix_ops_mpi.hpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/perf_tests/kurakin_min_rows_matrix.cpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_mpi.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/func_tests/kurakin_min_rows_matrix.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/include/kurakin_min_rows_matrix_ops_seq.hpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/perf_tests/kurakin_min_rows_matrix.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/src/kurakin_min_rows_matrix_ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#322 Fix func tests. Чижов Максим. Задача 1. Вариант 16. Нахождение максимальных значений по столбца матрицы
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/func_tests/main.cpp
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/include/ops_mpi.hpp
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/perf_tests/main.cpp
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/func_tests/main.cpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/include/ops_seq.hpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/perf_tests/main.cpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#359 Шуравина Оксана. Задача 2. Вариант 27. Повышение контраста
  tasks/mpi/shuravina_o_contrast/func_tests/main.cpp
  tasks/mpi/shuravina_o_contrast/include/ops_mpi.hpp
  tasks/mpi/shuravina_o_contrast/perf_tests/main.cpp
  tasks/mpi/shuravina_o_contrast/src/ops_mpi.cpp
  tasks/seq/shuravina_o_contrast/func_tests/main.cpp
  tasks/seq/shuravina_o_contrast/include/ops_seq.hpp
  tasks/seq/shuravina_o_contrast/perf_tests/main.cpp
  tasks/seq/shuravina_o_contrast/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#386 Седова Ольга. Задача 2. Вариант 16. Ленточная вертикальная схема умножения матрицы на вектор
  tasks/mpi/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
  tasks/mpi/sedova_o_vertical_ribbon_scheme/include/ops_mpi.hpp
  tasks/mpi/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
  tasks/mpi/sedova_o_vertical_ribbon_scheme/src/ops_mpi.cpp
  tasks/seq/sedova_o_vertical_ribbon_scheme/func_tests/main.cpp
  tasks/seq/sedova_o_vertical_ribbon_scheme/include/ops_seq.hpp
  tasks/seq/sedova_o_vertical_ribbon_scheme/perf_tests/main.cpp
  tasks/seq/sedova_o_vertical_ribbon_scheme/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#399 Сомов Иван. Задача №2. Вариант 15. Ленточная горизонтальная схема
  tasks/mpi/somov_i_horizontal_scheme/func_tests/main.cpp
  tasks/mpi/somov_i_horizontal_scheme/include/ops_mpi.hpp
  tasks/mpi/somov_i_horizontal_scheme/perf_tests/main.cpp
  tasks/mpi/somov_i_horizontal_scheme/src/ops_mpi.cpp
  tasks/seq/somov_i_horizontal_scheme/func_tests/main.cpp
  tasks/seq/somov_i_horizontal_scheme/include/ops_seq.hpp
  tasks/seq/somov_i_horizontal_scheme/perf_tests/main.cpp
  tasks/seq/somov_i_horizontal_scheme/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#405 Revert "Бессонов Егор. Задача 21. Интегрирование – метод Монте-Карло."
  tasks/mpi/bessonov_e_integration_monte_carlo/func_tests/main.cpp
  tasks/mpi/bessonov_e_integration_monte_carlo/include/ops_mpi.hpp
  tasks/mpi/bessonov_e_integration_monte_carlo/perf_tests/main.cpp
  tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
  tasks/seq/bessonov_e_integration_monte_carlo/func_tests/main.cpp
  tasks/seq/bessonov_e_integration_monte_carlo/include/ops_seq.hpp
  tasks/seq/bessonov_e_integration_monte_carlo/perf_tests/main.cpp
  tasks/seq/bessonov_e_integration_monte_carlo/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#371 Ковальчук Александр. Задача 2. Вариант 15. Ленточная горизонтальная схема
  tasks/mpi/kovalchuk_a_horizontal_tape_scheme/func_tests/main.cpp
  tasks/mpi/kovalchuk_a_horizontal_tape_scheme/include/ops_mpi.hpp
  tasks/mpi/kovalchuk_a_horizontal_tape_scheme/perf_tests/main.cpp
  tasks/mpi/kovalchuk_a_horizontal_tape_scheme/src/ops_mpi.cpp
  tasks/seq/kovalchuk_a_horizontal_tape_scheme/func_tests/main.cpp
  tasks/seq/kovalchuk_a_horizontal_tape_scheme/include/ops_seq.hpp
  tasks/seq/kovalchuk_a_horizontal_tape_scheme/perf_tests/main.cpp
  tasks/seq/kovalchuk_a_horizontal_tape_scheme/src/ops_seq.cpp
Labels: approved - Arseniy

#415 Ермолаев Владислав. Задача 3. Вариант 7. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).
  tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/func_tests/main.cpp
  tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/include/ops_mpi.hpp
  tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/perf_tests/main.cpp
  tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/src/ops_mpi.cpp
  tasks/seq/ermolaev_v_multidimensional_integral_rectangle/func_tests/main.cpp
  tasks/seq/ermolaev_v_multidimensional_integral_rectangle/include/ops_seq.hpp
  tasks/seq/ermolaev_v_multidimensional_integral_rectangle/perf_tests/main.cpp
  tasks/seq/ermolaev_v_multidimensional_integral_rectangle/src/ops_seq.cpp
Labels: approved - Arseniy

#435 Капустин Иван Задача 2 Вариант 25 "пузырьковая" сортировка
  tasks/mpi/kapustin_i_bubble/func_tests/main.cpp
  tasks/mpi/kapustin_i_bubble/include/avg_mpi.hpp
  tasks/mpi/kapustin_i_bubble/perf_tests/main.cpp
  tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
  tasks/seq/kapustin_i_bubble/func_tests/main.cpp
  tasks/seq/kapustin_i_bubble/include/avg_seq.hpp
  tasks/seq/kapustin_i_bubble/perf_tests/main.cpp
  tasks/seq/kapustin_i_bubble/src/avg_seq.cpp
Labels: approved - Arseniy

#437 Чистов Алексей. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.
  tasks/mpi/chistov_a_convex_hull_image/func_tests/image.cpp
  tasks/mpi/chistov_a_convex_hull_image/include/image.hpp
  tasks/mpi/chistov_a_convex_hull_image/perf_tests/image.cpp
  tasks/mpi/chistov_a_convex_hull_image/src/image.cpp
  tasks/seq/chistov_a_convex_hull_image_seq/func_tests/image.cpp
  tasks/seq/chistov_a_convex_hull_image_seq/include/image.hpp
  tasks/seq/chistov_a_convex_hull_image_seq/perf_tests/image.cpp
  tasks/seq/chistov_a_convex_hull_image_seq/src/image.cpp
Labels: approved - Arseniy

#439 Хохлов Андрей. Задача 2. Вариант 23. Итеративные методы (Зейделя).
  tasks/mpi/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
  tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
  tasks/mpi/khokhlov_a_iterative_seidel_method/perf_tests/main_khokhlov.cpp
  tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
  tasks/seq/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
  tasks/seq/khokhlov_a_iterative_seidel_method/include/ops_seq_khokhlov.hpp
  tasks/seq/khokhlov_a_iterative_seidel_method/perf_tests/main_khokhlov.cpp
  tasks/seq/khokhlov_a_iterative_seidel_method/src/ops_seq_khokhlov.cpp
Labels: approved - Arseniy

#440 Ермилова Дарья. Задача 2. Вариант 6. Передача от всех одному (reduce).
  tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
  tasks/mpi/ermilova_d_custom_reduce/include/ops_mpi.hpp
  tasks/mpi/ermilova_d_custom_reduce/perf_tests/main.cpp
  tasks/mpi/ermilova_d_custom_reduce/src/ops_mpi.cpp
  tasks/mpi/ermilova_d_reduceMPI/func_tests/main.cpp
  tasks/mpi/ermilova_d_reduceMPI/include/ops_mpi.hpp
  tasks/mpi/ermilova_d_reduceMPI/perf_tests/main.cpp
  tasks/mpi/ermilova_d_reduceMPI/src/ops_mpi.cpp
Labels: approved - Arseniy

#441 Частов Вячеслав. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).
  tasks/mpi/chastov_v_bubble_sort/func_tests/main.cpp
  tasks/mpi/chastov_v_bubble_sort/include/ops_mpi.hpp
  tasks/mpi/chastov_v_bubble_sort/perf_tests/main.cpp
  tasks/mpi/chastov_v_bubble_sort/src/ops_mpi.cpp
  tasks/seq/chastov_v_bubble_sort/func_tests/main.cpp
  tasks/seq/chastov_v_bubble_sort/include/ops_seq.hpp
  tasks/seq/chastov_v_bubble_sort/perf_tests/main.cpp
  tasks/seq/chastov_v_bubble_sort/src/ops_seq.cpp
Labels: approved - Arseniy

#442 Белов Артём. Задача 2. Вариант 23. Итеративные методы (Зейделя).
  tasks/mpi/belov_a_gauss_seidel_iter_method/func_tests/main.cpp
  tasks/mpi/belov_a_gauss_seidel_iter_method/include/ops_mpi.hpp
  tasks/mpi/belov_a_gauss_seidel_iter_method/perf_tests/main.cpp
  tasks/mpi/belov_a_gauss_seidel_iter_method/src/ops_mpi.cpp
  tasks/seq/belov_a_gauss_seidel_iter_method/func_tests/main.cpp
  tasks/seq/belov_a_gauss_seidel_iter_method/include/ops_seq.hpp
  tasks/seq/belov_a_gauss_seidel_iter_method/perf_tests/main.cpp
  tasks/seq/belov_a_gauss_seidel_iter_method/src/ops_seq.cpp
Labels: approved - Arseniy

#444 Мурадов Майк. Задача 2. Вариант 5. Методы передачи сообщений "Передача от одного всем (broadcast)"
  tasks/mpi/muradov_m_broadcast/func_tests/main.cpp
  tasks/mpi/muradov_m_broadcast/include/ops_mpi.hpp
  tasks/mpi/muradov_m_broadcast/perf_tests/main.cpp
  tasks/mpi/muradov_m_broadcast/src/ops_mpi.cpp
Labels: approved - Arseniy

#443 Гордеева Таисия. Задача 2. Вариант 4. Спящий брадобрей
  tasks/mpi/gordeeva_t_sleeping_barber/func_tests/main.cpp
  tasks/mpi/gordeeva_t_sleeping_barber/include/ops_mpi.hpp
  tasks/mpi/gordeeva_t_sleeping_barber/perf_tests/main.cpp
  tasks/mpi/gordeeva_t_sleeping_barber/src/ops_mpi.cpp
Labels: approved - Arseniy, requires > 4 reviews

#445 Велиев Эльвин. Задача 2. Вариант 22. Итеративные методы (Якоби)
  tasks/mpi/veliev_e_jacobi_method/func_tests/main.cpp
  tasks/mpi/veliev_e_jacobi_method/include/ops_mpi.hpp
  tasks/mpi/veliev_e_jacobi_method/perf_tests/main.cpp
  tasks/mpi/veliev_e_jacobi_method/src/ops_mpi.cpp
  tasks/seq/veliev_e_jacobi_method/func_tests/main.cpp
  tasks/seq/veliev_e_jacobi_method/include/ops_seq.hpp
  tasks/seq/veliev_e_jacobi_method/perf_tests/main.cpp
  tasks/seq/veliev_e_jacobi_method/src/ops_seq.cpp
Labels: approved - Arseniy

#446 Владимирова Юлия. Задача 2. Вариант 9. Обобщенная передача от всех одному (gather)
  tasks/mpi/vladimirova_j_gather/func_tests/main.cpp
  tasks/mpi/vladimirova_j_gather/include/ops_mpi.hpp
  tasks/mpi/vladimirova_j_gather/include/ops_mpi_not_my_gather.hpp
  tasks/mpi/vladimirova_j_gather/perf_tests/main.cpp
  tasks/mpi/vladimirova_j_gather/src/ops_mpi.cpp
  tasks/mpi/vladimirova_j_gather/src/ops_mpi_not_my_gather.cpp
  tasks/seq/vladimirova_j_gather/func_tests/main.cpp
  tasks/seq/vladimirova_j_gather/include/ops_seq.hpp
  tasks/seq/vladimirova_j_gather/perf_tests/main.cpp
  tasks/seq/vladimirova_j_gather/src/ops_seq.cpp
Labels: approved - Arseniy

#448 Агафеев Сергей. Задача 1. Вариант 13. Максимальное значение элементов матрицы
  tasks/mpi/agafeev_s_max_of_vector_elements/func_tests/main.cpp
  tasks/mpi/agafeev_s_max_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/agafeev_s_max_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/agafeev_s_max_of_vector_elements/func_tests/main.cpp
  tasks/seq/agafeev_s_max_of_vector_elements/include/ops_seq.hpp
  tasks/seq/agafeev_s_max_of_vector_elements/perf_tests/main.cpp
  tasks/seq/agafeev_s_max_of_vector_elements/src/ops_seq.cpp
Labels: approved - Arseniy

#449 Варфоломеев Григорий. Задача 2. Вариант 8. Обобщенная передача от одного всем (scatter)
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/func_tests/main.cpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/include/ops_mpi.hpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/perf_tests/main.cpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter/src/ops_mpi.cpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter_custom/func_tests/main.cpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter_custom/include/ops_mpi.hpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter_custom/perf_tests/main.cpp
  tasks/mpi/varfolomeev_g_transfer_from_one_to_all_scatter_custom/src/ops_mpi.cpp
Labels: approved - Arseniy

#457 Чернова Наталья. Задача 2. Вариант 11. Топология сетей передачи данных кольцо
  tasks/mpi/chernova_n_topology_ring/func_tests/main.cpp
  tasks/mpi/chernova_n_topology_ring/include/ops_mpi.hpp
  tasks/mpi/chernova_n_topology_ring/perf_tests/main.cpp
  tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
Labels: approved - Arseniy

#458 Будажапова Екатерина. Задача 2. Вариант 15. Ленточная горизонтальная схема
  tasks/mpi/budazhapova_e_matrix_multiplication/func_tests/matrix_mult_func_tests_mpi.cpp
  tasks/mpi/budazhapova_e_matrix_multiplication/include/matrix_mult_mpi.hpp
  tasks/mpi/budazhapova_e_matrix_multiplication/perf_tests/matrix_mult_pref_tests_mpi.cpp
  tasks/mpi/budazhapova_e_matrix_multiplication/src/matrix_mult_mpi.cpp
  tasks/seq/budazhapova_e_matrix_multiplication/func_tests/matrix_mult_func_tests.cpp
  tasks/seq/budazhapova_e_matrix_multiplication/include/matrix_mult.hpp
  tasks/seq/budazhapova_e_matrix_multiplication/perf_tests/matrix_mult_pref_tests.cpp
  tasks/seq/budazhapova_e_matrix_multiplication/src/matrix_mult.cpp
Labels: approved - Arseniy

#460 Шляков Максим. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)
  tasks/mpi/shlyakov_m_allreduce/func_tests/main.cpp
  tasks/mpi/shlyakov_m_allreduce/include/ops_mpi.hpp
  tasks/mpi/shlyakov_m_allreduce/perf_tests/main.cpp
  tasks/mpi/shlyakov_m_allreduce/src/ops_mpi.cpp
Labels: approved - Arseniy

#461 Исправление на isend и irecv. Сорокин Андрей. Задача 2. Вариант 1. Производители-потребители
  tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
Labels: approved - Arseniy

#462 Зайцев Денис. Задача 2. 12 вариант. Топология сетей - звезда
  tasks/mpi/zaytsev_topology_star/func_tests/main.cpp
  tasks/mpi/zaytsev_topology_star/include/ops_mpi.hpp
  tasks/mpi/zaytsev_topology_star/perf_tests/main.cpp
  tasks/mpi/zaytsev_topology_star/src/ops_mpi.cpp
Labels: approved - Arseniy

#450 Золотарева Арина. Задача 2. Вариант 26. Сглаживание изображения
  tasks/mpi/zolotareva_a_smoothing_image/func_tests/main.cpp
  tasks/mpi/zolotareva_a_smoothing_image/include/ops_mpi.hpp
  tasks/mpi/zolotareva_a_smoothing_image/perf_tests/main.cpp
  tasks/mpi/zolotareva_a_smoothing_image/src/ops_mpi.cpp
  tasks/seq/zolotareva_a_smoothing_image/func_tests/main.cpp
  tasks/seq/zolotareva_a_smoothing_image/include/ops_seq.hpp
  tasks/seq/zolotareva_a_smoothing_image/perf_tests/main.cpp
  tasks/seq/zolotareva_a_smoothing_image/src/ops_seq.cpp
Labels: approved - Arseniy

#466 Бурыкин Михаил. Задача 2. Вариант 5. Методы передачи сообщений "Передача от одного всем (broadcast)"
  tasks/mpi/burykin_m_broadcast/func_tests/main.cpp
  tasks/mpi/burykin_m_broadcast/include/ops_mpi.hpp
  tasks/mpi/burykin_m_broadcast/perf_tests/main.cpp
  tasks/mpi/burykin_m_broadcast/src/ops_mpi.cpp
  tasks/mpi/burykin_m_broadcast_mpi/func_tests/main.cpp
  tasks/mpi/burykin_m_broadcast_mpi/include/ops_mpi.hpp
  tasks/mpi/burykin_m_broadcast_mpi/perf_tests/main.cpp
  tasks/mpi/burykin_m_broadcast_mpi/src/ops_mpi.cpp
Labels: approved - Arseniy

#468 Громов Алексей. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.
  tasks/mpi/gromov_a_gaussian_method_vertical/func_tests/main.cpp
  tasks/mpi/gromov_a_gaussian_method_vertical/include/ops_mpi.hpp
  tasks/mpi/gromov_a_gaussian_method_vertical/perf_tests/main.cpp
  tasks/mpi/gromov_a_gaussian_method_vertical/src/ops_mpi.cpp
  tasks/seq/gromov_a_gaussian_method_vertical/func_tests/main.cpp
  tasks/seq/gromov_a_gaussian_method_vertical/include/ops_seq.hpp
  tasks/seq/gromov_a_gaussian_method_vertical/perf_tests/main.cpp
  tasks/seq/gromov_a_gaussian_method_vertical/src/ops_seq.cpp
Labels: approved - Arseniy

#470 Кабалова Валерия. Задача 2. Вариант 6. Передача от всех одному (reduce).
  tasks/mpi/kabalova_v_mpi_reduce/func_tests/kabalova_mpi_reduce_func_tests.cpp
  tasks/mpi/kabalova_v_mpi_reduce/include/kabalova_mpi_reduce.hpp
  tasks/mpi/kabalova_v_mpi_reduce/perf_tests/kabalova_mpi_reduce_perf_tests.cpp
  tasks/mpi/kabalova_v_mpi_reduce/src/kabalova_mpi_reduce.cpp
  tasks/mpi/kabalova_v_my_reduce/func_tests/kabalova_my_reduce_func_tests.cpp
  tasks/mpi/kabalova_v_my_reduce/include/kabalova_my_reduce.hpp
  tasks/mpi/kabalova_v_my_reduce/perf_tests/kabalova_my_reduce_perf_tests.cpp
  tasks/mpi/kabalova_v_my_reduce/src/kabalova_my_reduce.cpp
Labels: approved - Arseniy

#472 Тараканов Денис. Задача 2. Вариант 11. Топология сети Кольцо
  tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
  tasks/mpi/tarakanov_d_ring_topology/include/ops_mpi.hpp
  tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
  tasks/mpi/tarakanov_d_ring_topology/src/ops_mpi.cpp
Labels: approved - Arseniy

#474 Корнеева Екатерина. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)
  tasks/mpi/korneeva_e_average_of_vector_elements/func_tests/main.cpp
  tasks/mpi/korneeva_e_average_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/korneeva_e_average_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/korneeva_e_average_of_vector_elements/src/ops_mpi.cpp
Labels: approved - Arseniy

#475 Бесхмельнова Ксения. Задача 3. Вариант 25. Построение выпуклой оболочки – проход Джарвиса.
  tasks/mpi/beskhmelnova_k_jarvis_march/func_tests/main.cpp
  tasks/mpi/beskhmelnova_k_jarvis_march/include/jarvis_march.hpp
  tasks/mpi/beskhmelnova_k_jarvis_march/perf_tests/main.cpp
  tasks/mpi/beskhmelnova_k_jarvis_march/src/jarvis_march.cpp
  tasks/seq/beskhmelnova_k_jarvis_march/func_tests/main.cpp
  tasks/seq/beskhmelnova_k_jarvis_march/include/jarvis_march.hpp
  tasks/seq/beskhmelnova_k_jarvis_march/perf_tests/main.cpp
  tasks/seq/beskhmelnova_k_jarvis_march/src/jarvis_march.cpp
Labels: approved - Arseniy

#480 Федоров Матвей. Задача 2. Вариант 6. Передача от всех одному (reduce)
  tasks/mpi/matthew_fyodorov_reduce/func_tests/main.cpp
  tasks/mpi/matthew_fyodorov_reduce/include/ops_mpi.hpp
  tasks/mpi/matthew_fyodorov_reduce/perf_tests/main.cpp
  tasks/mpi/matthew_fyodorov_reduce/src/ops_mpi.cpp
  tasks/mpi/matthew_fyodorov_reduce_custom/func_tests/main.cpp
  tasks/mpi/matthew_fyodorov_reduce_custom/include/ops_mpi.hpp
  tasks/mpi/matthew_fyodorov_reduce_custom/perf_tests/main.cpp
  tasks/mpi/matthew_fyodorov_reduce_custom/src/ops_mpi.cpp
Labels: approved - Arseniy

#482 Суворов Дмитрий. Задача 2. Вариант 10. Топология сети "Линейка".
  tasks/mpi/suvorov_d_linear_topology/func_tests/line_topo_f_tests.cpp
  tasks/mpi/suvorov_d_linear_topology/include/linear_topology.hpp
  tasks/mpi/suvorov_d_linear_topology/perf_tests/line_topo_p_tests.cpp
  tasks/mpi/suvorov_d_linear_topology/src/linear_topology.cpp
Labels: approved - Arseniy

#489 [FIX] removed logs from CI
  tasks/mpi/ermolaev_v_allreduce_my/include/test_funcs.hpp
Labels: approved - Arseniy

#487 Иванов Михаил. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
  tasks/mpi/ivanov_m_gauss_horizontal/func_tests/main.cpp
  tasks/mpi/ivanov_m_gauss_horizontal/include/ops_mpi.hpp
  tasks/mpi/ivanov_m_gauss_horizontal/perf_tests/main.cpp
  tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
  tasks/seq/ivanov_m_gauss_horizontal/func_tests/main.cpp
  tasks/seq/ivanov_m_gauss_horizontal/include/ops_seq.hpp
  tasks/seq/ivanov_m_gauss_horizontal/perf_tests/main.cpp
  tasks/seq/ivanov_m_gauss_horizontal/src/ops_seq.cpp
Labels: approved - Arseniy

#490 Шарамыгина Ирина. Задача 2. Вариант 10. Линейная топология передачи данных
  tasks/mpi/sharamygina_i_line_topology/func_tests/main.cpp
  tasks/mpi/sharamygina_i_line_topology/include/ops_mpi.h
  tasks/mpi/sharamygina_i_line_topology/perf_tests/main.cpp
  tasks/mpi/sharamygina_i_line_topology/src/ops_mpi.cpp
Labels: approved - Arseniy

#491 Кондратьев Ярослав. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.
  tasks/mpi/kondratev_ya_radix_sort_batcher_merge/func_tests/main.cpp
  tasks/mpi/kondratev_ya_radix_sort_batcher_merge/include/ops_mpi.hpp
  tasks/mpi/kondratev_ya_radix_sort_batcher_merge/perf_tests/main.cpp
  tasks/mpi/kondratev_ya_radix_sort_batcher_merge/src/ops_mpi.cpp
  tasks/seq/kondratev_ya_radix_sort_batcher_merge/func_tests/main.cpp
  tasks/seq/kondratev_ya_radix_sort_batcher_merge/include/ops_seq.hpp
  tasks/seq/kondratev_ya_radix_sort_batcher_merge/perf_tests/main.cpp
  tasks/seq/kondratev_ya_radix_sort_batcher_merge/src/ops_seq.cpp
Labels: approved - Arseniy

#492 Сдобнов Владимир. Задача 2. Вариант 22. Итеративный метод Якоби.
  tasks/mpi/Sdobnov_V_iteration_method_yakoby/func_tests/main.cpp
  tasks/mpi/Sdobnov_V_iteration_method_yakoby/include/ops_mpi.hpp
  tasks/mpi/Sdobnov_V_iteration_method_yakoby/perf_tests/main.cpp
  tasks/mpi/Sdobnov_V_iteration_method_yakoby/src/ops_mpi.cpp
  tasks/seq/Sdobnov_V_iteration_method_yakoby/func_tests/main.cpp
  tasks/seq/Sdobnov_V_iteration_method_yakoby/include/ops_seq.hpp
  tasks/seq/Sdobnov_V_iteration_method_yakoby/perf_tests/main.cpp
  tasks/seq/Sdobnov_V_iteration_method_yakoby/src/ops_seq.cpp
Labels: approved - Arseniy

#498 Fix Revert. Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_mpi.hpp
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
  tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_seq.hpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
  tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
Labels: approved - Arseniy

#500 Наумов Богдан. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).
  tasks/mpi/naumov_b_bubble_sort/func_tests/main.cpp
  tasks/mpi/naumov_b_bubble_sort/include/ops_mpi.hpp
  tasks/mpi/naumov_b_bubble_sort/perf_tests/main.cpp
  tasks/mpi/naumov_b_bubble_sort/src/ops_mpi.cpp
  tasks/seq/naumov_b_bubble_sort/func_tests/main.cpp
  tasks/seq/naumov_b_bubble_sort/include/ops_seq.hpp
  tasks/seq/naumov_b_bubble_sort/perf_tests/main.cpp
  tasks/seq/naumov_b_bubble_sort/src/ops_seq.cpp
Labels: approved - Arseniy

#503 Fix Revert. Бесхмельнова Ксения. Задача 2. Вариант 3. Обедающие философы.
  tasks/mpi/beskhmelnova_k_dinning_philosophers/func_tests/main.cpp
  tasks/mpi/beskhmelnova_k_dinning_philosophers/include/dinning_philosophers.hpp
  tasks/mpi/beskhmelnova_k_dinning_philosophers/perf_tests/main.cpp
  tasks/mpi/beskhmelnova_k_dinning_philosophers/src/dinning_philosophers.cpp
Labels: approved - Arseniy

#506 Fix Revert. Созонов Илья. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
  tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
  tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/include/ops_seq.hpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/src/ops_seq.cpp
Labels: approved - Arseniy

#517 Revert. Шульпин Илья. Задача 2. Вариант 18. Умножение матриц, ленточная горизонтальная схема А, вертикальное В
  tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
  tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
  tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
  tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
  tasks/seq/shulpin_i_strip_hA_vB/func_tests/main.cpp
  tasks/seq/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
  tasks/seq/shulpin_i_strip_hA_vB/perf_tests/main.cpp
  tasks/seq/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
Labels: approved - Arseniy

#521 Дурыничев Дмитрий. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)
  tasks/mpi/durynichev_d_allreduce/func_tests/main.cpp
  tasks/mpi/durynichev_d_allreduce/include/ops_mpi.hpp
  tasks/mpi/durynichev_d_allreduce/perf_tests/main.cpp
  tasks/mpi/durynichev_d_allreduce/src/ops_mpi.cpp
  tasks/mpi/durynichev_d_custom_allreduce/func_tests/main.cpp
  tasks/mpi/durynichev_d_custom_allreduce/include/ops_mpi.hpp
  tasks/mpi/durynichev_d_custom_allreduce/perf_tests/main.cpp
  tasks/mpi/durynichev_d_custom_allreduce/src/ops_mpi.cpp
Labels: approved - Arseniy

#531 Fix Revert Филатьев Владислав. Задача 2. Вариант 23. Итеративные методы (Зейделя)
  tasks/mpi/filatev_v_metod_zedela/func_tests/main.cpp
  tasks/mpi/filatev_v_metod_zedela/include/ops_mpi.hpp
  tasks/mpi/filatev_v_metod_zedela/perf_tests/main.cpp
  tasks/mpi/filatev_v_metod_zedela/src/ops_mpi.cpp
  tasks/seq/filatev_v_metod_zedela/func_tests/main.cpp
  tasks/seq/filatev_v_metod_zedela/include/ops_seq.hpp
  tasks/seq/filatev_v_metod_zedela/perf_tests/main.cpp
  tasks/seq/filatev_v_metod_zedela/src/ops_seq.cpp
Labels: approved - Arseniy

#534 Коробейников Арсений. Задача 2. Вариант 18. Ленточная горизонтальная схема А, вертикальное В.
  tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/func_tests/main_korobeinikov.cpp
  tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/include/ops_mpi_korobeinikov.hpp
  tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/perf_tests/main_korobeinikov.cpp
  tasks/mpi/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_mpi_korobeinikov.cpp
  tasks/seq/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/func_tests/main_korobeinikov.cpp
  tasks/seq/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/include/ops_seq_korobeinikov.hpp
  tasks/seq/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/perf_tests/main_korobeinikov.cpp
  tasks/seq/korobeinikov_matrix_multiplication_horizontal_scheme_A_vertical_scheme_B/src/ops_seq_korobeinikov.cpp
Labels: approved - Arseniy

#547 Revert "Казунин Никита. Задача 2. Вариант 3. Обедающие философы." (#514)
  tasks/mpi/kazunin_n_dining_philosophers/func_tests/main.cpp
  tasks/mpi/kazunin_n_dining_philosophers/include/ops_mpi.hpp
  tasks/mpi/kazunin_n_dining_philosophers/perf_tests/main.cpp
  tasks/mpi/kazunin_n_dining_philosophers/src/ops_mpi.cpp
Labels: approved - Arseniy

#542 Прохоров Никита. Задача 2. Вариант 1. Задача «Производители-потребители».
  tasks/mpi/prokhorov_n_producer_customer/func_tests/main.cpp
  tasks/mpi/prokhorov_n_producer_customer/include/ops_mpi.hpp
  tasks/mpi/prokhorov_n_producer_customer/perf_tests/main.cpp
  tasks/mpi/prokhorov_n_producer_customer/src/ops_mpi.cpp
Labels: approved - Arseniy

#420 Матюнина Александра. Задача 2. Вариант 3. Задача: Обедающие философы
  tasks/mpi/matyunina_a_dining_philosophers/func_tests/main.cpp
  tasks/mpi/matyunina_a_dining_philosophers/include/ops_mpi.hpp
  tasks/mpi/matyunina_a_dining_philosophers/perf_tests/main.cpp
  tasks/mpi/matyunina_a_dining_philosophers/src/ops_mpi.cpp
Labels: approved - Alexander, approved - Arseniy

#483 REVERT Холин Кирилл. Задача 2. Вариант 23. Итеративные методы(Зейделя)
  tasks/mpi/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
  tasks/mpi/kholin_k_iterative_methods_Seidel/include/ops_mpi.hpp
  tasks/mpi/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
  tasks/mpi/kholin_k_iterative_methods_Seidel/src/ops_mpi.cpp
  tasks/seq/kholin_k_iterative_methods_Seidel/func_tests/main.cpp
  tasks/seq/kholin_k_iterative_methods_Seidel/include/ops_seq.hpp
  tasks/seq/kholin_k_iterative_methods_Seidel/perf_tests/main.cpp
  tasks/seq/kholin_k_iterative_methods_Seidel/src/ops_seq.cpp
Labels: wait ci, approved - Alexander, approved - Arseniy

#602 Revert "Revert "Ковалев Константин. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки)""
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/include/header.hpp
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/perf_tests/main.cpp
  tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/src/sourse.cpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/include/header.hpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/perf_tests/main.cpp
  tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/src/sourse.cpp
Labels: approved - Alexander, approved - Arseniy

#513 Fix revert Одинцов Михаил. Задача 1.Вариант 27 Подсчет числа несовпадающих символов двух строк
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/include/ops_mpi.hpp
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/include/ops_seq.hpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#618 Detect MPI buffer cluttering
  tasks/mpi/example/func_tests/main.cpp
  tasks/mpi/example/perf_tests/main.cpp
Labels: approved - Arseniy

#212 Лаврентьев Алексей. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора
  tasks/mpi/lavrentyev_a_alternation_count/func_tests/main.cpp
  tasks/mpi/lavrentyev_a_alternation_count/include/ops_mpi.hpp
  tasks/mpi/lavrentyev_a_alternation_count/perf_tests/main.cpp
  tasks/mpi/lavrentyev_a_alternation_count/src/ops_mpi.cpp
  tasks/seq/lavrentyev_a_alternation_count/func_tests/main.cpp
  tasks/seq/lavrentyev_a_alternation_count/include/ops_seq.hpp
  tasks/seq/lavrentyev_a_alternation_count/perf_tests/main.cpp
  tasks/seq/lavrentyev_a_alternation_count/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy, requires > 4 reviews

#421 Сорокин Андрей. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема
  tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
  tasks/mpi/sorokin_a_graham_algorithm/include/ops_mpi.hpp
  tasks/mpi/sorokin_a_graham_algorithm/perf_tests/main.cpp
  tasks/mpi/sorokin_a_graham_algorithm/src/ops_mpi.cpp
  tasks/seq/sorokin_a_graham_algorithm/func_tests/main.cpp
  tasks/seq/sorokin_a_graham_algorithm/include/ops_seq.hpp
  tasks/seq/sorokin_a_graham_algorithm/perf_tests/main.cpp
  tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#522 Мухина Маргарита. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием
  tasks/mpi/muhina_m_shell_sort/func_tests/main.cpp
  tasks/mpi/muhina_m_shell_sort/include/ops_mpi.hpp
  tasks/mpi/muhina_m_shell_sort/perf_tests/main.cpp
  tasks/mpi/muhina_m_shell_sort/src/ops_mpi.cpp
  tasks/seq/muhina_m_shell_sort/func_tests/main.cpp
  tasks/seq/muhina_m_shell_sort/include/ops_seq.hpp
  tasks/seq/muhina_m_shell_sort/perf_tests/main.cpp
  tasks/seq/muhina_m_shell_sort/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#529 Revert "Revert "Гнитиенко Кирилл. Задача 2. Вариант 27. Повышение контраста изображения""
  tasks/mpi/gnitienko_k_contrast_enhancement/func_tests/main.cpp
  tasks/mpi/gnitienko_k_contrast_enhancement/include/ops_mpi.hpp
  tasks/mpi/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
  tasks/mpi/gnitienko_k_contrast_enhancement/src/ops_mpi.cpp
  tasks/seq/gnitienko_k_contrast_enhancement/func_tests/main.cpp
  tasks/seq/gnitienko_k_contrast_enhancement/include/ops_seq.hpp
  tasks/seq/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
  tasks/seq/gnitienko_k_contrast_enhancement/src/ops_seq.cpp
Labels: approved - Arseniy

#532 Казунин Никита. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.
  tasks/mpi/kazunin_n_quicksort_simple_merge/func_tests/main.cpp
  tasks/mpi/kazunin_n_quicksort_simple_merge/include/ops_mpi.hpp
  tasks/mpi/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
  tasks/mpi/kazunin_n_quicksort_simple_merge/src/ops_mpi.cpp
  tasks/seq/kazunin_n_quicksort_simple_merge/func_tests/main.cpp
  tasks/seq/kazunin_n_quicksort_simple_merge/include/ops_seq.hpp
  tasks/seq/kazunin_n_quicksort_simple_merge/perf_tests/main.cpp
  tasks/seq/kazunin_n_quicksort_simple_merge/src/ops_seq.cpp
Labels: approved - Arseniy

#535 Ясакова Татьяна. Задача 2. Вариант 6. Передача от всеx одному (reduce)
  tasks/mpi/yasakova_t_reduce/func_tests/main.cpp
  tasks/mpi/yasakova_t_reduce/include/ops_mpi.hpp
  tasks/mpi/yasakova_t_reduce/perf_tests/main.cpp
  tasks/mpi/yasakova_t_reduce/src/ops_mpi.cpp
  tasks/mpi/yasakova_t_reduce_custom/func_tests/main.cpp
  tasks/mpi/yasakova_t_reduce_custom/include/ops_mpi.hpp
  tasks/mpi/yasakova_t_reduce_custom/perf_tests/main.cpp
  tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
Labels: approved - Arseniy

#595 FIX. Дрождинов Дмитрий. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
  tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/include/ops_seq.hpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
  tasks/seq/drozhdinov_d_gauss_vertical_scheme/src/ops_seq.cpp
Labels: approved - Arseniy

#615 Revert "Чистов Алексей.Задача 2.Вариант 9. Обобщенная передача от всех одному(gather)."
  tasks/mpi/chistov_a_gather_boost/func_tests/gather_boost.cpp
  tasks/mpi/chistov_a_gather_boost/func_tests/sort_boost.cpp
  tasks/mpi/chistov_a_gather_boost/include/gather_boost.hpp
  tasks/mpi/chistov_a_gather_boost/include/sort_boost.hpp
  tasks/mpi/chistov_a_gather_boost/perf_tests/gather_boost.cpp
  tasks/mpi/chistov_a_gather_boost/perf_tests/sort_boost.cpp
  tasks/mpi/chistov_a_gather_boost/src/gather_boost.cpp
  tasks/mpi/chistov_a_gather_boost/src/sort_boost.cpp
  tasks/mpi/chistov_a_gather_my/func_tests/gather_my.cpp
  tasks/mpi/chistov_a_gather_my/func_tests/sort_my.cpp
  tasks/mpi/chistov_a_gather_my/include/gather_my.hpp
  tasks/mpi/chistov_a_gather_my/include/sort_my.hpp
  tasks/mpi/chistov_a_gather_my/perf_tests/gather_my.cpp
  tasks/mpi/chistov_a_gather_my/perf_tests/sort_my.cpp
  tasks/mpi/chistov_a_gather_my/src/gather_my.cpp
  tasks/mpi/chistov_a_gather_my/src/sort_my.cpp
Labels: approved - Arseniy

#620 Fix Revert "Revert "Казунин Никита. Задача 2. Вариант 3. Обедающие философы." (#514)" (#610)
  tasks/mpi/kazunin_n_dining_philosophers/func_tests/main.cpp
  tasks/mpi/kazunin_n_dining_philosophers/include/ops_mpi.hpp
  tasks/mpi/kazunin_n_dining_philosophers/perf_tests/main.cpp
  tasks/mpi/kazunin_n_dining_philosophers/src/ops_mpi.cpp
Labels: approved - Arseniy

#622 Агафеев Сергей. Задача 2. Вариант 10. Линейная топология сети.
  tasks/mpi/agafeev_s_linear_topology/func_tests/main.cpp
  tasks/mpi/agafeev_s_linear_topology/include/lintop_mpi.hpp
  tasks/mpi/agafeev_s_linear_topology/perf_tests/main.cpp
  tasks/mpi/agafeev_s_linear_topology/src/lintop_mpi.cpp
Labels: approved - Arseniy

#653 Fix Revert Шульпин Илья. Задача 2. Вариант 18. Умножение матриц, ленточная горизонтальная схема А, вертикальное В
  tasks/mpi/shulpin_i_strip_hA_vB/func_tests/main.cpp
  tasks/mpi/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
  tasks/mpi/shulpin_i_strip_hA_vB/perf_tests/main.cpp
  tasks/mpi/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
  tasks/seq/shulpin_i_strip_hA_vB/func_tests/main.cpp
  tasks/seq/shulpin_i_strip_hA_vB/include/strip_hA_vB.hpp
  tasks/seq/shulpin_i_strip_hA_vB/perf_tests/main.cpp
  tasks/seq/shulpin_i_strip_hA_vB/src/strip_hA_vB.cpp
Labels: approved - Arseniy

#658 Fix revert "Соцков Андрей. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А"
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/include/ops_mpi.hpp
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/perf_tests/main.cpp
  tasks/mpi/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_mpi.cpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/func_tests/main.cpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/include/ops_seq.hpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/perf_tests/main.cpp
  tasks/seq/sotskov_a_horizontal_strip_scheme_only_matrix_a_partitioned/src/ops_seq.cpp
Labels: approved - Arseniy

#660 Fix "Revert "Ковалев Константин. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.""
  tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
  tasks/mpi/kovalev_k_num_of_orderly_violations/include/header.hpp
  tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
  tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
Labels: approved - Arseniy

#673 Созонов Илья. Задача 3. Вариант 27. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.
  tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/func_tests/main.cpp
  tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/include/ops_mpi.hpp
  tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/perf_tests/main.cpp
  tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/src/ops_mpi.cpp
  tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/func_tests/main.cpp
  tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/include/ops_seq.hpp
  tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/perf_tests/main.cpp
  tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#505 Цацын Александр. Задача 3. Вариант 30. "Повышение контраста полутонового изображения посредством линейной растяжки гистограммы"
  tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
  tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/include/ops_mpi.hpp
  tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/perf_tests/main.cpp
  tasks/mpi/tsatsyn_a_increasing_contrast_by_histogram/src/ops_mpi.cpp
  tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/func_tests/main.cpp
  tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/include/ops_seq.hpp
  tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/perf_tests/main.cpp
  tasks/seq/tsatsyn_a_increasing_contrast_by_histogram/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#518 Золотарева Арина. Задача 3. Вариант 6. Решение систем линейных уравнений методом сопряженных градиентов.
  tasks/mpi/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
  tasks/mpi/zolotareva_a_SLE_gradient_method/include/ops_mpi.hpp
  tasks/mpi/zolotareva_a_SLE_gradient_method/perf_tests/main.cpp
  tasks/mpi/zolotareva_a_SLE_gradient_method/src/ops_mpi.cpp
  tasks/seq/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
  tasks/seq/zolotareva_a_SLE_gradient_method/include/ops_seq.hpp
  tasks/seq/zolotareva_a_SLE_gradient_method/perf_tests/main.cpp
  tasks/seq/zolotareva_a_SLE_gradient_method/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#525 Ковалев Константин. Задача 3. Вариант 7. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).
  tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/func_tests/main.cpp
  tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/include/header.hpp
  tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/perf_tests/main.cpp
  tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/src/sourse.cpp
  tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/func_tests/main.cpp
  tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/include/header.hpp
  tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/perf_tests/main.cpp
  tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/src/sourse.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#526 Соцков Андрей. Задача 3. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.
  tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
  tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_mpi.hpp
  tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
  tasks/mpi/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_mpi.cpp
  tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/func_tests/main.cpp
  tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/include/ops_seq.hpp
  tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/perf_tests/main.cpp
  tasks/seq/sotskov_a_radix_sort_for_numbers_type_double_with_simple_merging/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#528 Дрождинов Дмитрий. Задача 3. Вариант 2. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.
  tasks/mpi/drozhdinov_d_mult_matrix_fox/func_tests/main.cpp
  tasks/mpi/drozhdinov_d_mult_matrix_fox/include/ops_mpi.hpp
  tasks/mpi/drozhdinov_d_mult_matrix_fox/perf_tests/main.cpp
  tasks/mpi/drozhdinov_d_mult_matrix_fox/src/ops_mpi.cpp
  tasks/seq/drozhdinov_d_mult_matrix_fox/func_tests/main.cpp
  tasks/seq/drozhdinov_d_mult_matrix_fox/include/ops_seq.hpp
  tasks/seq/drozhdinov_d_mult_matrix_fox/perf_tests/main.cpp
  tasks/seq/drozhdinov_d_mult_matrix_fox/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#538 Лопатин Илья. Задача 3. Вариант 15. Быстрая сортировка с чётно-нечётным слиянием Бэтчера.
  tasks/mpi/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsMPI.cpp
  tasks/mpi/lopatin_i_quick_batcher_mergesort/include/quickBatcherMergesortHeaderMPI.hpp
  tasks/mpi/lopatin_i_quick_batcher_mergesort/perf_tests/quickBatcherMergesortPerfTestsMPI.cpp
  tasks/mpi/lopatin_i_quick_batcher_mergesort/src/quickBatcherMergesortMPI.cpp
  tasks/seq/lopatin_i_quick_batcher_mergesort/func_tests/quickBatcherMergesortFuncTestsSeq.cpp
  tasks/seq/lopatin_i_quick_batcher_mergesort/include/quickBatcherMergesortHeaderSeq.hpp
  tasks/seq/lopatin_i_quick_batcher_mergesort/perf_tests/quickBatcherMergesortPerfTestsSeq.cpp
  tasks/seq/lopatin_i_quick_batcher_mergesort/src/quickBatcherMergesortSeq.cpp
Labels: on review - Alexander, approved - Arseniy

#541 Малышев Антон. Задача 3. Вариант 13. Многошаговая схема решения двумерных задач глобальной оптимизации. Распараллеливание по характеристикам.
  tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/func_tests/main.cpp
  tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/include/ops_mpi.hpp
  tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/perf_tests/main.cpp
  tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/src/ops_mpi.cpp
  tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/func_tests/main.cpp
  tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/include/ops_seq.hpp
  tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/perf_tests/main.cpp
  tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#545 Шурыгин Сергей. Задача №3. Вариант №28. Линейная фильтрация изображений. Ядро Гаусса 3x3 (блочное разбиение).
  tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/func_tests/main.cpp
  tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/include/ops_mpi.hpp
  tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/perf_tests/main.cpp
  tasks/mpi/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_mpi.cpp
  tasks/seq/shurigin_lin_filtr_razbien_bloch_gaus_3x3/func_tests/main.cpp
  tasks/seq/shurigin_lin_filtr_razbien_bloch_gaus_3x3/include/ops_seq.hpp
  tasks/seq/shurigin_lin_filtr_razbien_bloch_gaus_3x3/perf_tests/main.cpp
  tasks/seq/shurigin_lin_filtr_razbien_bloch_gaus_3x3/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#550 Гусев Никита. Задача 3. Вариант 22. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры). С CRS графов
  tasks/mpi/gusev_n_dijkstras_algorithm/func_tests/main.cpp
  tasks/mpi/gusev_n_dijkstras_algorithm/include/ops_mpi.hpp
  tasks/mpi/gusev_n_dijkstras_algorithm/perf_tests/main.cpp
  tasks/mpi/gusev_n_dijkstras_algorithm/src/ops_mpi.cpp
  tasks/seq/gusev_n_dijkstras_algorithm/func_tests/main.cpp
  tasks/seq/gusev_n_dijkstras_algorithm/include/ops_seq.hpp
  tasks/seq/gusev_n_dijkstras_algorithm/perf_tests/main.cpp
  tasks/seq/gusev_n_dijkstras_algorithm/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#552 Сомов Иван. Задача №3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с чётно-нечётным слиянием Бэтчера
  tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
  tasks/mpi/somov_i_bitwise_sorting_batcher_merge/include/ops_mpi.hpp
  tasks/mpi/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
  tasks/mpi/somov_i_bitwise_sorting_batcher_merge/src/ops_mpi.cpp
  tasks/seq/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
  tasks/seq/somov_i_bitwise_sorting_batcher_merge/include/ops_seq.hpp
  tasks/seq/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
  tasks/seq/somov_i_bitwise_sorting_batcher_merge/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#606 Fix Revert. Мухина Маргарита. Задача 2. Вариант 15. Ленточная горизонтальная схема
  tasks/mpi/muhina_m_horizontal_cheme/func_tests/main.cpp
  tasks/mpi/muhina_m_horizontal_cheme/include/ops_mpi.hpp
  tasks/mpi/muhina_m_horizontal_cheme/perf_tests/main.cpp
  tasks/mpi/muhina_m_horizontal_cheme/src/ops_mpi.cpp
  tasks/seq/muhina_m_horizontal_cheme/func_tests/main.cpp
  tasks/seq/muhina_m_horizontal_cheme/include/ops_seq.hpp
  tasks/seq/muhina_m_horizontal_cheme/perf_tests/main.cpp
  tasks/seq/muhina_m_horizontal_cheme/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#641 Шуравина Оксана. Задача 1 Вариант 21. Интегрирование – метод Монте-Карло.
  tasks/mpi/shuravina_o_monte_carlo/func_tests/main.cpp
  tasks/mpi/shuravina_o_monte_carlo/include/ops_mpi.hpp
  tasks/mpi/shuravina_o_monte_carlo/perf_tests/main.cpp
  tasks/mpi/shuravina_o_monte_carlo/src/ops_mpi.cpp
  tasks/seq/shuravina_o_monte_carlo/func_tests/main.cpp
  tasks/seq/shuravina_o_monte_carlo/include/ops_seq.hpp
  tasks/seq/shuravina_o_monte_carlo/perf_tests/main.cpp
  tasks/seq/shuravina_o_monte_carlo/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#530 REVERT Ермилова Дарья. Задача 1. Вариант 14. Минимальное значение матрицы.
  tasks/mpi/ermilova_d_min_element_matrix/func_tests/main.cpp
  tasks/mpi/ermilova_d_min_element_matrix/include/ops_mpi.hpp
  tasks/mpi/ermilova_d_min_element_matrix/perf_tests/main.cpp
  tasks/mpi/ermilova_d_min_element_matrix/src/ops_mpi.cpp
  tasks/seq/ermilova_d_min_element_matrix/func_tests/main.cpp
  tasks/seq/ermilova_d_min_element_matrix/include/ops_seq.hpp
  tasks/seq/ermilova_d_min_element_matrix/perf_tests/main.cpp
  tasks/seq/ermilova_d_min_element_matrix/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#556 Одинцов Михаил. Задача 3 Вариант 13 Многошаговая система решения двухмерных задач глобальной оптимизации. Распараллеливание по характеристикам
  tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/func_tests/main.cpp
  tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/include/ops_mpi.hpp
  tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/perf_tests/main.cpp
  tasks/mpi/Odintsov_M_GlobalOptimizationSpecifications/src/ops_mpi.cpp
  tasks/seq/Odintsov_M_GlobalOptimizationSpecifications/func_tests/main.cpp
  tasks/seq/Odintsov_M_GlobalOptimizationSpecifications/include/ops_seq.hpp
  tasks/seq/Odintsov_M_GlobalOptimizationSpecifications/perf_tests/main.cpp
  tasks/seq/Odintsov_M_GlobalOptimizationSpecifications/src/ops_seq.cpp
Labels: wait ci, approved - Alexander, approved - Arseniy

#626 Зиновьев Александр Задача 1 Вариант 12 Сумма значений по столбцам матрицы
  tasks/mpi/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
  tasks/mpi/zinoviev_a_sum_cols_matrix/include/ops_mpi.hpp
  tasks/mpi/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
  tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
  tasks/seq/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
  tasks/seq/zinoviev_a_sum_cols_matrix/include/ops_seq.hpp
  tasks/seq/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
  tasks/seq/zinoviev_a_sum_cols_matrix/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#438 Шведова Виталина. Задача 3. Вариант 9. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона)
  tasks/mpi/shvedova_v_mult_int_simpson/func_tests/main.cpp
  tasks/mpi/shvedova_v_mult_int_simpson/include/ops_mpi.hpp
  tasks/mpi/shvedova_v_mult_int_simpson/perf_tests/main.cpp
  tasks/mpi/shvedova_v_mult_int_simpson/src/ops_mpi.cpp
  tasks/seq/shvedova_v_multi_integral_simpson/func_tests/main.cpp
  tasks/seq/shvedova_v_multi_integral_simpson/include/ops_seq.hpp
  tasks/seq/shvedova_v_multi_integral_simpson/perf_tests/main.cpp
  tasks/seq/shvedova_v_multi_integral_simpson/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#463 Грудзин Константин. Задача 3. Вариант 10. Интегрирование методом Монте-Карло многомерных интегралов
  tasks/mpi/grudzin_k_monte_carlo/func_tests/gmc_ftests.cpp
  tasks/mpi/grudzin_k_monte_carlo/include/gmc_include.hpp
  tasks/mpi/grudzin_k_monte_carlo/perf_tests/gmc_ptests.cpp
  tasks/mpi/grudzin_k_monte_carlo/src/gmc_src.cpp
  tasks/seq/grudzin_k_monte_carlo/func_tests/main.cpp
  tasks/seq/grudzin_k_monte_carlo/include/ops_seq.hpp
  tasks/seq/grudzin_k_monte_carlo/perf_tests/main.cpp
  tasks/seq/grudzin_k_monte_carlo/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy
