Repository learning-process/ppc-2024-autumn, pull requests merged in 2024-11, with the labels that each got.

#39 Холин Кирилл. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению элементов вектора.
  tasks/mpi/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
  tasks/mpi/kholin_k_vector_neighbor_diff_elems/include/ops_mpi.hpp
  tasks/mpi/kholin_k_vector_neighbor_diff_elems/perf_tests/main.cpp
  tasks/mpi/kholin_k_vector_neighbor_diff_elems/src/ops_mpi.cpp
  tasks/seq/kholin_k_vector_neighbor_diff_elems/func_tests/main.cpp
  tasks/seq/kholin_k_vector_neighbor_diff_elems/include/ops_seq.hpp
  tasks/seq/kholin_k_vector_neighbor_diff_elems/perf_tests/main.cpp
  tasks/seq/kholin_k_vector_neighbor_diff_elems/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#52 Казунин Никита. Задача 1. Вариант 23. Подсчёт частоты символа в строке.
  tasks/mpi/kazunin_n_count_freq_a_char_in_string/func_tests/main.cpp
  tasks/mpi/kazunin_n_count_freq_a_char_in_string/include/ops_mpi.hpp
  tasks/mpi/kazunin_n_count_freq_a_char_in_string/perf_tests/main.cpp
  tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
  tasks/seq/kazunin_n_count_freq_a_char_in_string/func_tests/main.cpp
  tasks/seq/kazunin_n_count_freq_a_char_in_string/include/ops_seq.hpp
  tasks/seq/kazunin_n_count_freq_a_char_in_string/perf_tests/main.cpp
  tasks/seq/kazunin_n_count_freq_a_char_in_string/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#61 Титов Семён. Задача 1. Вариант 1. Сумма элементов вектора.
  tasks/mpi/titov_s_vector_sum/func_tests/main.cpp
  tasks/mpi/titov_s_vector_sum/include/ops_mpi.hpp
  tasks/mpi/titov_s_vector_sum/perf_tests/main.cpp
  tasks/mpi/titov_s_vector_sum/src/ops_mpi.cpp
  tasks/seq/titov_s_vector_sum/func_tests/main.cpp
  tasks/seq/titov_s_vector_sum/include/ops_seq.hpp
  tasks/seq/titov_s_vector_sum/perf_tests/main.cpp
  tasks/seq/titov_s_vector_sum/src/ops_seq.cpp
Labels: wait approvers

#78 Fix tests with number of processes: 3, 5, 7, 8
  tasks/mpi/chistov_a_sum_of_matrix_elements/src/ops_mpi.cpp
Labels: approved - Arseniy

#17 Соловьев Данила. Задача 1. Вариант 3. Максимальное значение элементов вектора.
  tasks/mpi/solovyev_d_vector_max/func_tests/main.cpp
  tasks/mpi/solovyev_d_vector_max/include/header.hpp
  tasks/mpi/solovyev_d_vector_max/perf_tests/main.cpp
  tasks/mpi/solovyev_d_vector_max/src/source.cpp
  tasks/seq/solovyev_d_vector_max/func_tests/main.cpp
  tasks/seq/solovyev_d_vector_max/include/header.hpp
  tasks/seq/solovyev_d_vector_max/perf_tests/main.cpp
  tasks/seq/solovyev_d_vector_max/src/source.cpp
Labels: wait approvers

#54 Грудзин Константин. Задача 1. Вариант 7. Нахождение наиболее близких по значению соседних элементов вектора.
  tasks/mpi/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
  tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/include/ops_seq.hpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#68 Харин Матвей. Задача 1. Вариант 25. Подсчет числа предложений в строке.
  tasks/mpi/kharin_m_number_of_sentences_mpi/func_tests/main.cpp
  tasks/mpi/kharin_m_number_of_sentences_mpi/include/ops_mpi.hpp
  tasks/mpi/kharin_m_number_of_sentences_mpi/perf_tests/main.cpp
  tasks/mpi/kharin_m_number_of_sentences_mpi/src/ops_mpi.cpp
  tasks/seq/kharin_m_number_of_sentences_seq/func_tests/main.cpp
  tasks/seq/kharin_m_number_of_sentences_seq/include/ops_seq.hpp
  tasks/seq/kharin_m_number_of_sentences_seq/perf_tests/main.cpp
  tasks/seq/kharin_m_number_of_sentences_seq/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#70 Владимирова Юлия. Задача 1. Вариант 13. Максимальное значение элементов матрицы.
  tasks/mpi/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
  tasks/mpi/vladimirova_j_max_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/vladimirova_j_max_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
  tasks/seq/vladimirova_j_max_of_vector_elements/include/ops_seq.hpp
  tasks/seq/vladimirova_j_max_of_vector_elements/perf_tests/main.cpp
  tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#69 Кудряшова Ирина. Задача 1. Вариант 9. Скалярное произведение векторов.
  tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
  tasks/mpi/kudryashova_i_vector_dot_product/include/vectorDotProductMPI.hpp
  tasks/mpi/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductMPIPerfTests.cpp
  tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
  tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
  tasks/seq/kudryashova_i_vector_dot_product/include/vectorDotProductSeq.hpp
  tasks/seq/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductSeqPerfTests.cpp
  tasks/seq/kudryashova_i_vector_dot_product/src/vectorDotProductSeq.cpp
Labels: approved - Alexander, on review - Arseniy

#51 Васенков Андрей. Задача 1. Вариант 23. Подсчет частоты символа в строке
  tasks/mpi/vasenkov_a_char_freq/func_tests/main.cpp
  tasks/mpi/vasenkov_a_char_freq/include/ops_mpi.hpp
  tasks/mpi/vasenkov_a_char_freq/perf_tests/main.cpp
  tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
  tasks/seq/vasenkov_a_char_freq/func_tests/main.cpp
  tasks/seq/vasenkov_a_char_freq/include/ops_seq.hpp
  tasks/seq/vasenkov_a_char_freq/perf_tests/main.cpp
  tasks/seq/vasenkov_a_char_freq/src/ops_seq.cpp
Labels: wait approvers

#84 Мурадов Майк. Задача 1. Вариант 22. Подсчет числа буквенных символов в строке
  tasks/mpi/muradov_m_count_alpha_chars/func_tests/main.cpp
  tasks/mpi/muradov_m_count_alpha_chars/include/ops_mpi.hpp
  tasks/mpi/muradov_m_count_alpha_chars/perf_tests/main.cpp
  tasks/mpi/muradov_m_count_alpha_chars/src/ops_mpi.cpp
  tasks/seq/muradov_m_count_alpha_chars/func_tests/main.cpp
  tasks/seq/muradov_m_count_alpha_chars/include/ops_seq.hpp
  tasks/seq/muradov_m_count_alpha_chars/perf_tests/main.cpp
  tasks/seq/muradov_m_count_alpha_chars/src/ops_seq.cpp
Labels: approved - Alexander

#58 Гнитиенко Кирилл. Задача 1. Вариант 11. Сумма значений по строкам матрицы
  tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/func_tests/main.cpp
  tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/include/ops_mpi.hpp
  tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/perf_tests/main.cpp
  tasks/mpi/gnitienko_k_sum_values_by_rows_matrix/src/ops_mpi.cpp
  tasks/seq/gnitienko_k_sum_values_by_rows_matrix/func_tests/main.cpp
  tasks/seq/gnitienko_k_sum_values_by_rows_matrix/include/ops_seq.hpp
  tasks/seq/gnitienko_k_sum_values_by_rows_matrix/perf_tests/main.cpp
  tasks/seq/gnitienko_k_sum_values_by_rows_matrix/src/ops_seq.cpp
Labels: wait approvers

#62 Милованкин Максим. Задача 1. Вариант 1. Сумма элементов вектора.
  tasks/mpi/milovankin_m_sum_of_vector_elements/func_tests/main.cpp
  tasks/mpi/milovankin_m_sum_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/milovankin_m_sum_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/milovankin_m_sum_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/milovankin_m_sum_of_vector_elements/func_tests/main.cpp
  tasks/seq/milovankin_m_sum_of_vector_elements/include/ops_seq.hpp
  tasks/seq/milovankin_m_sum_of_vector_elements/perf_tests/main.cpp
  tasks/seq/milovankin_m_sum_of_vector_elements/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#44 Чижов Максим. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/func_tests/main.cpp
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/include/ops_mpi.hpp
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/perf_tests/main.cpp
  tasks/mpi/chizhov_m_max_values_by_columns_matrix/src/ops_mpi.cpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/func_tests/main.cpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/include/ops_seq.hpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/perf_tests/main.cpp
  tasks/seq/chizhov_m_max_values_by_columns_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#56 Ворошилов Виталий. Задача 1. Вариант 22. Подсчёт числа буквенных символов в строке.
  tasks/mpi/voroshilov_v_num_of_alphabetic_chars/func_tests/main.cpp
  tasks/mpi/voroshilov_v_num_of_alphabetic_chars/include/ops_mpi.hpp
  tasks/mpi/voroshilov_v_num_of_alphabetic_chars/perf_tests/main.cpp
  tasks/mpi/voroshilov_v_num_of_alphabetic_chars/src/ops_mpi.cpp
  tasks/seq/voroshilov_v_num_of_alphabetic_chars/func_tests/main.cpp
  tasks/seq/voroshilov_v_num_of_alphabetic_chars/include/ops_seq.hpp
  tasks/seq/voroshilov_v_num_of_alphabetic_chars/perf_tests/main.cpp
  tasks/seq/voroshilov_v_num_of_alphabetic_chars/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#65 ‎Рамс Сергей. Задача 1. Вариант 23. Подсчет частоты символа в строке
  tasks/mpi/rams_s_char_frequency/func_tests/main.cpp
  tasks/mpi/rams_s_char_frequency/include/ops_mpi.hpp
  tasks/mpi/rams_s_char_frequency/perf_tests/main.cpp
  tasks/mpi/rams_s_char_frequency/src/ops_mpi.cpp
  tasks/seq/rams_s_char_frequency/func_tests/main.cpp
  tasks/seq/rams_s_char_frequency/include/ops_seq.hpp
  tasks/seq/rams_s_char_frequency/perf_tests/main.cpp
  tasks/seq/rams_s_char_frequency/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#76 Кондратьев Ярослав. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы
  tasks/mpi/kondratev_ya_max_col_matrix/func_tests/main.cpp
  tasks/mpi/kondratev_ya_max_col_matrix/include/ops_mpi.hpp
  tasks/mpi/kondratev_ya_max_col_matrix/perf_tests/main.cpp
  tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
  tasks/seq/kondratev_ya_max_col_matrix/func_tests/main.cpp
  tasks/seq/kondratev_ya_max_col_matrix/include/ops_seq.hpp
  tasks/seq/kondratev_ya_max_col_matrix/perf_tests/main.cpp
  tasks/seq/kondratev_ya_max_col_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#80 Николаев Роман. Задача 1. Вариант 20. Интегрирование - метод трапеций.
  tasks/mpi/nikolaev_r_trapezoidal_integral/func_tests/main.cpp
  tasks/mpi/nikolaev_r_trapezoidal_integral/include/ops_mpi.hpp
  tasks/mpi/nikolaev_r_trapezoidal_integral/perf_tests/main.cpp
  tasks/mpi/nikolaev_r_trapezoidal_integral/src/ops_mpi.cpp
  tasks/seq/nikolaev_r_trapezoidal_integral/func_tests/main.cpp
  tasks/seq/nikolaev_r_trapezoidal_integral/include/ops_seq.hpp
  tasks/seq/nikolaev_r_trapezoidal_integral/perf_tests/main.cpp
  tasks/seq/nikolaev_r_trapezoidal_integral/src/ops_seq.cpp
Labels: approved - Arseniy

#86 Ермилова Дарья. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
  tasks/mpi/ermilova_d_min_element_matrix/func_tests/main.cpp
  tasks/mpi/ermilova_d_min_element_matrix/include/ops_mpi.hpp
  tasks/mpi/ermilova_d_min_element_matrix/perf_tests/main.cpp
  tasks/mpi/ermilova_d_min_element_matrix/src/ops_mpi.cpp
  tasks/seq/ermilova_d_min_element_matrix/func_tests/main.cpp
  tasks/seq/ermilova_d_min_element_matrix/include/ops_seq.hpp
  tasks/seq/ermilova_d_min_element_matrix/perf_tests/main.cpp
  tasks/seq/ermilova_d_min_element_matrix/src/ops_seq.cpp
Labels: approved - Arseniy

#90 Борисов Сергей. Задача 1. Вариант 11. Сумма значений по строкам матрицы
  tasks/mpi/borisov_s_sum_of_rows/func_tests/main.cpp
  tasks/mpi/borisov_s_sum_of_rows/include/ops_mpi.hpp
  tasks/mpi/borisov_s_sum_of_rows/perf_tests/main.cpp
  tasks/mpi/borisov_s_sum_of_rows/src/ops_mpi.cpp
  tasks/seq/borisov_s_sum_of_rows/func_tests/main.cpp
  tasks/seq/borisov_s_sum_of_rows/include/ops_seq.hpp
  tasks/seq/borisov_s_sum_of_rows/perf_tests/main.cpp
  tasks/seq/borisov_s_sum_of_rows/src/ops_seq.cpp
Labels: approved - Arseniy

#93 Созонов Илья. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
  tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
  tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/include/ops_seq.hpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/seq/sozonov_i_nearest_neighbor_elements/src/ops_seq.cpp
Labels: approved - Arseniy

#100 Коротин Егор. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
  tasks/mpi/korotin_e_min_val_matrix/func_tests/main.cpp
  tasks/mpi/korotin_e_min_val_matrix/include/ops_mpi.hpp
  tasks/mpi/korotin_e_min_val_matrix/perf_tests/main.cpp
  tasks/mpi/korotin_e_min_val_matrix/src/ops_mpi.cpp
  tasks/seq/korotin_e_min_val_matrix/func_tests/main.cpp
  tasks/seq/korotin_e_min_val_matrix/include/ops_seq.hpp
  tasks/seq/korotin_e_min_val_matrix/perf_tests/main.cpp
  tasks/seq/korotin_e_min_val_matrix/src/ops_seq.cpp
Labels: approved - Arseniy

#177 [CI] Run performance testing every 4 hours
  .github/workflows/main.yml
Labels: enhancement

#104 Смирнов Илья. Задача 1. Вариант 19. Интегрирование методом прямоугольников.
  tasks/mpi/smirnov_i_integration_by_rectangles/func_tests/main.cpp
  tasks/mpi/smirnov_i_integration_by_rectangles/include/ops_mpi.hpp
  tasks/mpi/smirnov_i_integration_by_rectangles/perf_tests/main.cpp
  tasks/mpi/smirnov_i_integration_by_rectangles/src/ops_mpi.cpp
  tasks/seq/smirnov_i_integration_by_rectangles/func_tests/main.cpp
  tasks/seq/smirnov_i_integration_by_rectangles/include/ops_seq.hpp
  tasks/seq/smirnov_i_integration_by_rectangles/perf_tests/main.cpp
  tasks/seq/smirnov_i_integration_by_rectangles/src/ops_seq.cpp
Labels: approved - Arseniy

#109 Шляков Максим. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы
  tasks/mpi/shlyakov_m_min_value_of_row/func_tests/main.cpp
  tasks/mpi/shlyakov_m_min_value_of_row/include/ops_mpi.hpp
  tasks/mpi/shlyakov_m_min_value_of_row/perf_tests/main.cpp
  tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
  tasks/seq/shlyakov_m_min_value_of_row/func_tests/main.cpp
  tasks/seq/shlyakov_m_min_value_of_row/include/ops_seq.hpp
  tasks/seq/shlyakov_m_min_value_of_row/perf_tests/main.cpp
  tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
Labels: approved - Arseniy

#114 Гусейнов Эмил. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
  tasks/mpi/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
  tasks/mpi/guseynov_e_check_lex_order_of_two_string/include/ops_mpi.hpp
  tasks/mpi/guseynov_e_check_lex_order_of_two_string/perf_tests/main.cpp
  tasks/mpi/guseynov_e_check_lex_order_of_two_string/src/ops_mpi.cpp
  tasks/seq/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
  tasks/seq/guseynov_e_check_lex_order_of_two_string/include/ops_seq.hpp
  tasks/seq/guseynov_e_check_lex_order_of_two_string/perf_tests/main.cpp
  tasks/seq/guseynov_e_check_lex_order_of_two_string/src/ops_seq.cpp
Labels: approved - Arseniy

#115 Ясакова Татьяна. Задача 1. Вариант 14. Минимальное значение элементов матрицы.
  tasks/mpi/yasakova_t_min_of_vector_elements/func_tests/main_yasakova.cpp
  tasks/mpi/yasakova_t_min_of_vector_elements/include/ops_mpi_yasakova.hpp
  tasks/mpi/yasakova_t_min_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/yasakova_t_min_of_vector_elements/src/ops_mpi_yasakova.cpp
  tasks/seq/yasakova_t_min_of_vector_elements/func_tests/main_yasakova.cpp
  tasks/seq/yasakova_t_min_of_vector_elements/include/ops_seq_yasakova.hpp
  tasks/seq/yasakova_t_min_of_vector_elements/perf_tests/main_yasakova.cpp
  tasks/seq/yasakova_t_min_of_vector_elements/src/ops_seq_yasakova.cpp
Labels: approved - Arseniy

#126 Грудзин Константин. Задача 1. Вариант 7. Нахождение наиболее близких по значению соседних элементов вектора.
  tasks/mpi/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
  tasks/mpi/grudzin_k_nearest_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/grudzin_k_nearest_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/func_tests/main.cpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/include/ops_seq.hpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/seq/grudzin_k_nearest_neighbor_elements/src/ops_seq.cpp
Labels: approved - Arseniy

#127 Куракин Матвей. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/include/ops_mpi.hpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/perf_tests/main.cpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/ops_mpi.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/include/ops_seq.hpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/perf_tests/main.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/src/ops_seq.cpp
Labels: approved - Arseniy

#131 Одинцов Михаил. Вариант 27 Подсчет числа несовпадающих символов двух строк
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/include/ops_mpi.hpp
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
  tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/include/ops_seq.hpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
  tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/src/ops_seq.cpp
Labels: approved - Arseniy

#137 Фролова Елизавета. Задача 1. Вариант 22. Подсчет числа буквенных символов в строке
  tasks/mpi/frolova_e_num_of_letters/func_tests/main.cpp
  tasks/mpi/frolova_e_num_of_letters/include/ops_mpi.hpp
  tasks/mpi/frolova_e_num_of_letters/perf_tests/main.cpp
  tasks/mpi/frolova_e_num_of_letters/src/ops_mpi.cpp
  tasks/seq/frolova_e_num_of_letters/func_tests/main.cpp
  tasks/seq/frolova_e_num_of_letters/include/ops_seq.hpp
  tasks/seq/frolova_e_num_of_letters/perf_tests/main.cpp
  tasks/seq/frolova_e_num_of_letters/src/ops_seq.cpp
Labels: approved - Arseniy

#129 Ковалев Константин. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.
  tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
  tasks/mpi/kovalev_k_num_of_orderly_violations/include/header.hpp
  tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
  tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp
  tasks/seq/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
  tasks/seq/kovalev_k_num_of_orderly_violations/include/header.hpp
  tasks/seq/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
  tasks/seq/kovalev_k_num_of_orderly_violations/src/sourse.cpp
Labels: approved - Arseniy

#140 Порошин Владислав. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы
  tasks/mpi/poroshin_v_find_min_val_row_matrix/func_tests/main.cpp
  tasks/mpi/poroshin_v_find_min_val_row_matrix/include/ops_mpi.hpp
  tasks/mpi/poroshin_v_find_min_val_row_matrix/perf_tests/main.cpp
  tasks/mpi/poroshin_v_find_min_val_row_matrix/src/ops_mpi.cpp
  tasks/seq/poroshin_v_find_min_val_row_matrix/func_tests/main.cpp
  tasks/seq/poroshin_v_find_min_val_row_matrix/include/ops_seq.hpp
  tasks/seq/poroshin_v_find_min_val_row_matrix/perf_tests/main.cpp
  tasks/seq/poroshin_v_find_min_val_row_matrix/src/ops_seq.cpp
Labels: approved - Arseniy

#142 Ануфриев Даниил. Задача 1. Вариант 3. Максимальное значение элементов вектора.
  tasks/mpi/anufriev_d_max_of_vector_elements/func_tests/main_anufriev.cpp
  tasks/mpi/anufriev_d_max_of_vector_elements/include/ops_mpi_anufriev.hpp
  tasks/mpi/anufriev_d_max_of_vector_elements/perf_tests/main_anufriev.cpp
  tasks/mpi/anufriev_d_max_of_vector_elements/src/ops_mpi_anufriev.cpp
  tasks/seq/anufriev_d_max_of_vector_elements/func_tests/main_anufriev.cpp
  tasks/seq/anufriev_d_max_of_vector_elements/include/ops_seq_anufriev.hpp
  tasks/seq/anufriev_d_max_of_vector_elements/perf_tests/main_anufriev.cpp
  tasks/seq/anufriev_d_max_of_vector_elements/src/ops_seq_anufriev.cpp
Labels: approved - Arseniy

#144 Ведерникова Ксения. Задача 1. Вариант 24. Подсчет числа слов в строке
  tasks/mpi/vedernikova_k_word_num_in_str/func_tests/main.cpp
  tasks/mpi/vedernikova_k_word_num_in_str/include/ops_mpi.hpp
  tasks/mpi/vedernikova_k_word_num_in_str/perf_tests/main.cpp
  tasks/mpi/vedernikova_k_word_num_in_str/src/ops_mpi.cpp
  tasks/seq/vedernikova_k_word_num_in_str/func_tests/main.cpp
  tasks/seq/vedernikova_k_word_num_in_str/include/ops_seq.hpp
  tasks/seq/vedernikova_k_word_num_in_str/perf_tests/main.cpp
  tasks/seq/vedernikova_k_word_num_in_str/src/ops_seq.cpp
Labels: approved - Arseniy

#67 Морозов Егор. Задача 1. Вариант17. Нахождение минимальных значений по строкам матрицы
  tasks/mpi/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
  tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
  tasks/mpi/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
  tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
  tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
  tasks/seq/morozov_e_min_val_in_rows_matrix/include/ops_seq.hpp
  tasks/seq/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
  tasks/seq/morozov_e_min_val_in_rows_matrix/src/ops_seq.cpp
Labels: wait approvers, requires > 4 reviews

#101 Козлова Екатерина. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
  tasks/mpi/kozlova_e_lexic_order/func_tests/main.cpp
  tasks/mpi/kozlova_e_lexic_order/include/ops_mpi.hpp
  tasks/mpi/kozlova_e_lexic_order/perf_tests/main.cpp
  tasks/mpi/kozlova_e_lexic_order/src/ops_mpi.cpp
  tasks/seq/kozlova_e_lexic_order/func_tests/main.cpp
  tasks/seq/kozlova_e_lexic_order/include/ops_seq.hpp
  tasks/seq/kozlova_e_lexic_order/perf_tests/main.cpp
  tasks/seq/kozlova_e_lexic_order/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#173 Кошкин Никита. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.
  tasks/mpi/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
  tasks/mpi/koshkin_n_sum_values_by_columns_matrix/include/ops_mpi.hpp
  tasks/mpi/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
  tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
  tasks/seq/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
  tasks/seq/koshkin_n_sum_values_by_columns_matrix/include/ops_seq.hpp
  tasks/seq/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
  tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
Labels: approved - Alexander

#192 Бурыкин Михаил. Задача 1. Вариант 24. Подсчёт числа слов в строке.
  tasks/mpi/burykin_m_word_count/func_tests/main.cpp
  tasks/mpi/burykin_m_word_count/include/ops_mpi.hpp
  tasks/mpi/burykin_m_word_count/perf_tests/main.cpp
  tasks/mpi/burykin_m_word_count/src/ops_mpi.cpp
  tasks/seq/burykin_m_word_count/func_tests/main.cpp
  tasks/seq/burykin_m_word_count/include/ops_seq.hpp
  tasks/seq/burykin_m_word_count/perf_tests/main.cpp
  tasks/seq/burykin_m_word_count/src/ops_seq.cpp
Labels: approved - Alexander

#162 Иванов Михаил. Задача 1. Вариант 20. Интегрирование – метод трапеций.
  tasks/mpi/ivanov_m_integration_trapezoid/func_tests/main.cpp
  tasks/mpi/ivanov_m_integration_trapezoid/include/ops_mpi.hpp
  tasks/mpi/ivanov_m_integration_trapezoid/perf_tests/main.cpp
  tasks/mpi/ivanov_m_integration_trapezoid/src/ops_mpi.cpp
  tasks/seq/ivanov_m_integration_trapezoid/func_tests/main.cpp
  tasks/seq/ivanov_m_integration_trapezoid/include/ops_seq.hpp
  tasks/seq/ivanov_m_integration_trapezoid/perf_tests/main.cpp
  tasks/seq/ivanov_m_integration_trapezoid/src/ops_seq.cpp
Labels: approved - Alexander

#141 Кошкин Матвей. Задача 1. Вариант 9. Скалярное произведение векторов
  tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
  tasks/mpi/koshkin_m_scalar_product_of_vectors/include/ops_mpi.hpp
  tasks/mpi/koshkin_m_scalar_product_of_vectors/perf_tests/main.cpp
  tasks/mpi/koshkin_m_scalar_product_of_vectors/src/ops_mpi.cpp
  tasks/seq/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
  tasks/seq/koshkin_m_scalar_product_of_vectors/include/ops_seq.hpp
  tasks/seq/koshkin_m_scalar_product_of_vectors/perf_tests/main.cpp
  tasks/seq/koshkin_m_scalar_product_of_vectors/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#135 Садиков Иван. Задача 1. Вариант 12. Сумма значений по столбцам матрицы
  tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
  tasks/mpi/sadikov_I_sum_values_by_columns_matrix/include/ops_mpi.h
  tasks/mpi/sadikov_I_sum_values_by_columns_matrix/perf_tests/main.cpp
  tasks/mpi/sadikov_I_sum_values_by_columns_matrix/src/mpi_src.cpp
  tasks/seq/sadikov_I_sum_values_by_columns_matrix/func_tests/seq_func_tests.cpp
  tasks/seq/sadikov_I_sum_values_by_columns_matrix/include/sq_task.h
  tasks/seq/sadikov_I_sum_values_by_columns_matrix/perf_tests/main.cpp
  tasks/seq/sadikov_I_sum_values_by_columns_matrix/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#130 Тюрин Михаил. Задача 1. Вариант 25. Подсчет числа предложений в строке.
  tasks/mpi/tyurin_m_count_sentences_in_string/func_tests/main.cpp
  tasks/mpi/tyurin_m_count_sentences_in_string/include/ops_mpi.hpp
  tasks/mpi/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
  tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
  tasks/seq/tyurin_m_count_sentences_in_string/func_tests/main.cpp
  tasks/seq/tyurin_m_count_sentences_in_string/include/ops_seq.hpp
  tasks/seq/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
  tasks/seq/tyurin_m_count_sentences_in_string/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy, requires > 4 reviews

#111 Васильев Сергей. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
  tasks/mpi/vasilev_s_nearest_neighbor_elements/func_tests/main.cpp
  tasks/mpi/vasilev_s_nearest_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/vasilev_s_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/vasilev_s_nearest_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/vasilev_s_nearest_neighbor_elements/func_tests/main.cpp
  tasks/seq/vasilev_s_nearest_neighbor_elements/include/ops_seq.hpp
  tasks/seq/vasilev_s_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/seq/vasilev_s_nearest_neighbor_elements/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#153 Строганов Михаил. Задача 1. Вариант 22. Нахождение числа буквенных символов в строке.
  tasks/mpi/stroganov_m_count_symbols_in_string/func_tests/main.cpp
  tasks/mpi/stroganov_m_count_symbols_in_string/include/ops_mpi.hpp
  tasks/mpi/stroganov_m_count_symbols_in_string/perf_tests/main.cpp
  tasks/mpi/stroganov_m_count_symbols_in_string/src/ops_mpi.cpp
  tasks/seq/stroganov_m_count_symbols_in_string/func_tests/main.cpp
  tasks/seq/stroganov_m_count_symbols_in_string/include/ops_seq.hpp
  tasks/seq/stroganov_m_count_symbols_in_string/perf_tests/main.cpp
  tasks/seq/stroganov_m_count_symbols_in_string/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy, requires > 4 reviews

#116 Береснев Антон. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.
  tasks/mpi/beresnev_a_min_values_by_matrix_columns/func_tests/main.cpp
  tasks/mpi/beresnev_a_min_values_by_matrix_columns/include/ops_mpi.hpp
  tasks/mpi/beresnev_a_min_values_by_matrix_columns/perf_tests/main.cpp
  tasks/mpi/beresnev_a_min_values_by_matrix_columns/src/ops_mpi.cpp
  tasks/seq/beresnev_a_min_values_by_matrix_columns/func_tests/main.cpp
  tasks/seq/beresnev_a_min_values_by_matrix_columns/include/ops_seq.hpp
  tasks/seq/beresnev_a_min_values_by_matrix_columns/perf_tests/main.cpp
  tasks/seq/beresnev_a_min_values_by_matrix_columns/src/ops_seq.cpp
Labels: wait approvers

#150 Тышкевич Артем. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.
  tasks/mpi/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
  tasks/mpi/tyshkevich_a_num_of_orderly_violations/include/ops_mpi.hpp
  tasks/mpi/tyshkevich_a_num_of_orderly_violations/perf_tests/main.cpp
  tasks/mpi/tyshkevich_a_num_of_orderly_violations/src/ops_mpi.cpp
  tasks/seq/tyshkevich_a_num_of_orderly_violations/func_tests/main.cpp
  tasks/seq/tyshkevich_a_num_of_orderly_violations/include/ops_seq.hpp
  tasks/seq/tyshkevich_a_num_of_orderly_violations/perf_tests/main.cpp
  tasks/seq/tyshkevich_a_num_of_orderly_violations/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#167 Кудряшова Ирина. Задача 1. Вариант 9. Скалярное произведение векторов
  tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
  tasks/mpi/kudryashova_i_vector_dot_product/include/vectorDotProductMPI.hpp
  tasks/mpi/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductMPIPerfTests.cpp
  tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
  tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
  tasks/seq/kudryashova_i_vector_dot_product/include/vectorDotProductSeq.hpp
  tasks/seq/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductSeqPerfTests.cpp
  tasks/seq/kudryashova_i_vector_dot_product/src/vectorDotProductSeq.cpp
Labels: wait approvers

#190 Соловьев Данила. Задача 1. Вариант 3. Максимальное значение элементов вектора.
  tasks/mpi/solovyev_d_vector_max/func_tests/main.cpp
  tasks/mpi/solovyev_d_vector_max/include/header.hpp
  tasks/mpi/solovyev_d_vector_max/perf_tests/main.cpp
  tasks/mpi/solovyev_d_vector_max/src/source.cpp
  tasks/seq/solovyev_d_vector_max/func_tests/main.cpp
  tasks/seq/solovyev_d_vector_max/include/header.hpp
  tasks/seq/solovyev_d_vector_max/perf_tests/main.cpp
  tasks/seq/solovyev_d_vector_max/src/source.cpp
Labels: wait approvers

#102 Петров Олег. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора
  tasks/mpi/petrov_o_num_of_alternations_signs/func_tests/main.cpp
  tasks/mpi/petrov_o_num_of_alternations_signs/include/ops_mpi.hpp
  tasks/mpi/petrov_o_num_of_alternations_signs/perf_tests/main.cpp
  tasks/mpi/petrov_o_num_of_alternations_signs/src/ops_mpi.cpp
  tasks/seq/petrov_o_num_of_alternations_signs/func_tests/main.cpp
  tasks/seq/petrov_o_num_of_alternations_signs/include/ops_seq.hpp
  tasks/seq/petrov_o_num_of_alternations_signs/perf_tests/main.cpp
  tasks/seq/petrov_o_num_of_alternations_signs/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#132 Петров Артём. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.
  tasks/mpi/petrov_a_nearest_neighbor_elements/func_tests/main.cpp
  tasks/mpi/petrov_a_nearest_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/petrov_a_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/petrov_a_nearest_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/petrov_a_nearest_neighbor_elements/func_tests/main.cpp
  tasks/seq/petrov_a_nearest_neighbor_elements/include/ops_seq.hpp
  tasks/seq/petrov_a_nearest_neighbor_elements/perf_tests/main.cpp
  tasks/seq/petrov_a_nearest_neighbor_elements/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy, requires > 4 reviews

#145 Сидорина Полина. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.
  tasks/mpi/sidorina_p_check_lexicographic_order/func_tests/main.cpp
  tasks/mpi/sidorina_p_check_lexicographic_order/include/ops_mpi.hpp
  tasks/mpi/sidorina_p_check_lexicographic_order/perf_tests/main.cpp
  tasks/mpi/sidorina_p_check_lexicographic_order/src/ops_mpi.cpp
  tasks/seq/sidorina_p_check_lexicographic_order/func_tests/main.cpp
  tasks/seq/sidorina_p_check_lexicographic_order/include/ops_seq.hpp
  tasks/seq/sidorina_p_check_lexicographic_order/perf_tests/main.cpp
  tasks/seq/sidorina_p_check_lexicographic_order/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#147 Алпутов Иван. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
  tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
  tasks/mpi/alputov_i_most_different_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/alputov_i_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/alputov_i_most_different_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
  tasks/seq/alputov_i_most_different_neighbor_elements/include/ops_seq.hpp
  tasks/seq/alputov_i_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/seq/alputov_i_most_different_neighbor_elements/src/ops_seq.cpp
Labels: approved - Arseniy

#149 Белов Артём. Задача 1. Вариант 13. Максимальное значение элементов матрицы
  tasks/mpi/belov_a_max_value_of_matrix_elements/func_tests/main.cpp
  tasks/mpi/belov_a_max_value_of_matrix_elements/include/ops_mpi.hpp
  tasks/mpi/belov_a_max_value_of_matrix_elements/perf_tests/main.cpp
  tasks/mpi/belov_a_max_value_of_matrix_elements/src/ops_mpi.cpp
  tasks/seq/belov_a_max_value_of_matrix_elements/func_tests/main.cpp
  tasks/seq/belov_a_max_value_of_matrix_elements/include/ops_seq.hpp
  tasks/seq/belov_a_max_value_of_matrix_elements/perf_tests/main.cpp
  tasks/seq/belov_a_max_value_of_matrix_elements/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#166 Суворов Дмитрий. Задача 1. Вариант 1. Сумма элементов вектора.
  tasks/mpi/suvorov_d_sum_of_vector_elements/func_tests/main.cpp
  tasks/mpi/suvorov_d_sum_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/suvorov_d_sum_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/suvorov_d_sum_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/suvorov_d_sum_of_vector_elements/func_tests/main.cpp
  tasks/seq/suvorov_d_sum_of_vector_elements/include/vec.hpp
  tasks/seq/suvorov_d_sum_of_vector_elements/perf_tests/main.cpp
  tasks/seq/suvorov_d_sum_of_vector_elements/src/vec.cpp
Labels: on review - Alexander, approved - Arseniy, requires > 4 reviews

#181 Ковальчук Александр. Задача 1. Вариант 13. Максимальное значение элементов матрицы.
  tasks/mpi/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
  tasks/mpi/kovalchuk_a_max_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/kovalchuk_a_max_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/kovalchuk_a_max_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/kovalchuk_a_max_of_vector_elements/func_tests/main.cpp
  tasks/seq/kovalchuk_a_max_of_vector_elements/include/ops_seq.hpp
  tasks/seq/kovalchuk_a_max_of_vector_elements/perf_tests/main.cpp
  tasks/seq/kovalchuk_a_max_of_vector_elements/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy, requires > 4 reviews

#194 Сдобнов Владимир. Задача 1. Вариант 10. Сумма элементов матрицы.
  tasks/mpi/Sdobnov_V_sum_of_vector_elements/func_tests/main.cpp
  tasks/mpi/Sdobnov_V_sum_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/Sdobnov_V_sum_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/Sdobnov_V_sum_of_vector_elements/func_tests/main.cpp
  tasks/seq/Sdobnov_V_sum_of_vector_elements/include/ops_seq.hpp
  tasks/seq/Sdobnov_V_sum_of_vector_elements/perf_tests/main.cpp
  tasks/seq/Sdobnov_V_sum_of_vector_elements/src/ops_seq.cpp
Labels: approved - Arseniy, requires > 4 reviews

#188 Отурин Александр. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
  tasks/mpi/oturin_a_max_values_by_rows_matrix/func_tests/main.cpp
  tasks/mpi/oturin_a_max_values_by_rows_matrix/include/ops_mpi.hpp
  tasks/mpi/oturin_a_max_values_by_rows_matrix/perf_tests/main.cpp
  tasks/mpi/oturin_a_max_values_by_rows_matrix/src/ops_mpi.cpp
  tasks/seq/oturin_a_max_values_by_rows_matrix/func_tests/main.cpp
  tasks/seq/oturin_a_max_values_by_rows_matrix/include/ops_seq.hpp
  tasks/seq/oturin_a_max_values_by_rows_matrix/perf_tests/main.cpp
  tasks/seq/oturin_a_max_values_by_rows_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy, requires > 4 reviews

#232 fix Revert "Волочаев Серафим Задача 1. Вариант 27: Подсчет числа несовпадающих символов двух строк"
  tasks/mpi/volochaev_s_count_characters_27/func_tests/main.cpp
  tasks/mpi/volochaev_s_count_characters_27/include/ops_mpi.hpp
  tasks/mpi/volochaev_s_count_characters_27/perf_tests/main.cpp
  tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
  tasks/seq/volochaev_s_count_characters_27/func_tests/main.cpp
  tasks/seq/volochaev_s_count_characters_27/include/ops_seq.hpp
  tasks/seq/volochaev_s_count_characters_27/perf_tests/main.cpp
  tasks/seq/volochaev_s_count_characters_27/src/ops_seq.cpp
Labels: approved - Arseniy

#112 Седова Ольга. Задача 1. Вариант 13. Максимальное значение элементов матрицы.
  tasks/mpi/sedova_o_max_of_vector_elements/func_tests/main.cpp
  tasks/mpi/sedova_o_max_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/sedova_o_max_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/sedova_o_max_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/sedova_o_max_of_vector_elements/func_tests/main.cpp
  tasks/seq/sedova_o_max_of_vector_elements/include/ops_seq.hpp
  tasks/seq/sedova_o_max_of_vector_elements/perf_tests/main.cpp
  tasks/seq/sedova_o_max_of_vector_elements/src/ops_seq.cpp
Labels: wait approvers, requires > 4 reviews

#133 Цацын Александр. Задача 1. Вариант 9. Скалярное произведение векторов.
  tasks/mpi/tsatsyn_a_vector_dot_product/func_tests/main.cpp
  tasks/mpi/tsatsyn_a_vector_dot_product/include/ops_mpi.hpp
  tasks/mpi/tsatsyn_a_vector_dot_product/perf_tests/main.cpp
  tasks/mpi/tsatsyn_a_vector_dot_product/src/ops_mpi.cpp
  tasks/seq/tsatsyn_a_vector_dot_product/func_tests/main.cpp
  tasks/seq/tsatsyn_a_vector_dot_product/include/ops_seq.hpp
  tasks/seq/tsatsyn_a_vector_dot_product/perf_tests/main.cpp
  tasks/seq/tsatsyn_a_vector_dot_product/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#187 Коньков Иван. Задача 1. Вариант 24. Подсчет слов в строке.
  tasks/mpi/konkov_i_count_words/func_tests/main.cpp
  tasks/mpi/konkov_i_count_words/include/ops_mpi.hpp
  tasks/mpi/konkov_i_count_words/perf_tests/main.cpp
  tasks/mpi/konkov_i_count_words/src/ops_mpi.cpp
  tasks/seq/konkov_i_count_words/func_tests/main.cpp
  tasks/seq/konkov_i_count_words/include/ops_seq.hpp
  tasks/seq/konkov_i_count_words/perf_tests/main.cpp
  tasks/seq/konkov_i_count_words/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy, requires > 4 reviews

#175 Корнеева Екатерина. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.
  tasks/mpi/korneeva_e_num_of_orderly_violations/func_tests/main.cpp
  tasks/mpi/korneeva_e_num_of_orderly_violations/include/ops_mpi.hpp
  tasks/mpi/korneeva_e_num_of_orderly_violations/perf_tests/main.cpp
  tasks/mpi/korneeva_e_num_of_orderly_violations/src/ops_mpi.cpp
  tasks/seq/korneeva_e_num_of_orderly_violations/func_tests/main.cpp
  tasks/seq/korneeva_e_num_of_orderly_violations/include/ops_seq.hpp
  tasks/seq/korneeva_e_num_of_orderly_violations/perf_tests/main.cpp
  tasks/seq/korneeva_e_num_of_orderly_violations/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#200 Дормидонтов Егор. Задача 1. Вариант 18. Нахождение минимальных значений по столбцам матрицы.
  tasks/mpi/dormidontov_e_min_value_by_columns_mpi/func_tests/main.cpp
  tasks/mpi/dormidontov_e_min_value_by_columns_mpi/include/ops_mpi.hpp
  tasks/mpi/dormidontov_e_min_value_by_columns_mpi/perf_tests/main.cpp
  tasks/mpi/dormidontov_e_min_value_by_columns_mpi/src/ops_mpi.cpp
  tasks/seq/dormidontov_e_min_value_by_columns_seq/func_tests/main.cpp
  tasks/seq/dormidontov_e_min_value_by_columns_seq/include/ops_seq.hpp
  tasks/seq/dormidontov_e_min_value_by_columns_seq/perf_tests/main.cpp
  tasks/seq/dormidontov_e_min_value_by_columns_seq/src/ops_seq.cpp
Labels: approved - Arseniy

#161 Тараканов Денис. Задача 1. Вариант 20. Интегрирование - метод трапеций.
  tasks/mpi/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
  tasks/mpi/tarakanov_d_integration_the_trapezoid_method/include/ops_mpi.hpp
  tasks/mpi/tarakanov_d_integration_the_trapezoid_method/perf_tests/main.cpp
  tasks/mpi/tarakanov_d_integration_the_trapezoid_method/src/ops_mpi.cpp
  tasks/seq/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
  tasks/seq/tarakanov_d_integration_the_trapezoid_method/include/ops_seq.hpp
  tasks/seq/tarakanov_d_integration_the_trapezoid_method/perf_tests/main.cpp
  tasks/seq/tarakanov_d_integration_the_trapezoid_method/src/ops_seq.cpp
Labels: approved - Alexander

#239 Лаганина Елена. Задача 1. Вариант 12. Сумма значений матрицы по столбцам
  tasks/mpi/laganina_e_sum_values_by_columns_matrix/func_tests/main.cpp
  tasks/mpi/laganina_e_sum_values_by_columns_matrix/include/ops_mpi.hpp
  tasks/mpi/laganina_e_sum_values_by_columns_matrix/perf_tests/main.cpp
  tasks/mpi/laganina_e_sum_values_by_columns_matrix/src/ops_mpi.cpp
  tasks/seq/laganina_e_sum_values_by_columns_matrix/func_tests/main.cpp
  tasks/seq/laganina_e_sum_values_by_columns_matrix/include/ops_seq.hpp
  tasks/seq/laganina_e_sum_values_by_columns_matrix/perf_tests/main.cpp
  tasks/seq/laganina_e_sum_values_by_columns_matrix/src/ops_seq.cpp
Labels: approved - Alexander

#201 Малышев Антон. Задача 1. Вариант 11. Сумма значений по строкам матрицы
  tasks/mpi/malyshev_a_sum_rows_matrix/func_tests/main.cpp
  tasks/mpi/malyshev_a_sum_rows_matrix/include/ops_mpi.hpp
  tasks/mpi/malyshev_a_sum_rows_matrix/perf_tests/main.cpp
  tasks/mpi/malyshev_a_sum_rows_matrix/src/ops_mpi.cpp
  tasks/seq/malyshev_a_sum_rows_matrix/func_tests/main.cpp
  tasks/seq/malyshev_a_sum_rows_matrix/include/ops_seq.hpp
  tasks/seq/malyshev_a_sum_rows_matrix/perf_tests/main.cpp
  tasks/seq/malyshev_a_sum_rows_matrix/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#199 Зайцев Денис. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора
  tasks/mpi/zaytsev_d_num_of_alternations_signs/func_tests/main.cpp
  tasks/mpi/zaytsev_d_num_of_alternations_signs/include/ops_mpi.hpp
  tasks/mpi/zaytsev_d_num_of_alternations_signs/perf_tests/main.cpp
  tasks/mpi/zaytsev_d_num_of_alternations_signs/src/ops_mpi.cpp
  tasks/seq/zaytsev_d_num_of_alternations_signs/func_tests/main.cpp
  tasks/seq/zaytsev_d_num_of_alternations_signs/include/ops_seq.hpp
  tasks/seq/zaytsev_d_num_of_alternations_signs/perf_tests/main.cpp
  tasks/seq/zaytsev_d_num_of_alternations_signs/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#193 Revert "Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы"
  tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
  tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
  tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
  tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
Labels: wait approvers

#198 Золотарева Арина. Задача 1. Вариант 24. Подсчет числа слов в строке.
  tasks/mpi/zolotareva_a_count_of_words/func_tests/main.cpp
  tasks/mpi/zolotareva_a_count_of_words/include/ops_mpi.hpp
  tasks/mpi/zolotareva_a_count_of_words/perf_tests/main.cpp
  tasks/mpi/zolotareva_a_count_of_words/src/ops_mpi.cpp
  tasks/seq/zolotareva_a_count_of_words/func_tests/main.cpp
  tasks/seq/zolotareva_a_count_of_words/include/ops_seq.hpp
  tasks/seq/zolotareva_a_count_of_words/perf_tests/main.cpp
  tasks/seq/zolotareva_a_count_of_words/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#204 Зайцев Артем. Задача 1. Вариант 4. Минимальный элемент вектора.
  tasks/mpi/zaitsev_a_min_of_vector_elements/func_tests/main.cpp
  tasks/mpi/zaitsev_a_min_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/zaitsev_a_min_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/zaitsev_a_min_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/zaitsev_a_min_of_vector_elements/func_tests/main.cpp
  tasks/seq/zaitsev_a_min_of_vector_elements/include/ops_seq.hpp
  tasks/seq/zaitsev_a_min_of_vector_elements/perf_tests/main.cpp
  tasks/seq/zaitsev_a_min_of_vector_elements/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#221 Наумов Богдан Задача 1 вариант 18 Нахождение минимальных значений по столбцам матрицы
  tasks/mpi/naumov_b_min_colum_matrix/func_tests/main.cpp
  tasks/mpi/naumov_b_min_colum_matrix/include/ops_mpi.hpp
  tasks/mpi/naumov_b_min_colum_matrix/perf_tests/main.cpp
  tasks/mpi/naumov_b_min_colum_matrix/src/ops_mpi.cpp
  tasks/seq/naumov_b_min_colum_matrix/func_tests/main.cpp
  tasks/seq/naumov_b_min_colum_matrix/include/ops_seq.hpp
  tasks/seq/naumov_b_min_colum_matrix/perf_tests/main.cpp
  tasks/seq/naumov_b_min_colum_matrix/src/ops_seq.cpp
Labels: approved - Alexander

#249 Дурыничев Дмитрий. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
  tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
  tasks/mpi/durynichev_d_most_different_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/durynichev_d_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/durynichev_d_most_different_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
  tasks/seq/durynichev_d_most_different_neighbor_elements/include/ops_seq.hpp
  tasks/seq/durynichev_d_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/seq/durynichev_d_most_different_neighbor_elements/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#151 Наседкин Егор. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы.
  tasks/mpi/nasedkin_e_matrix_column_max_value/func_tests/main.cpp
  tasks/mpi/nasedkin_e_matrix_column_max_value/include/ops_mpi.hpp
  tasks/mpi/nasedkin_e_matrix_column_max_value/perf_tests/main.cpp
  tasks/mpi/nasedkin_e_matrix_column_max_value/src/ops_mpi.cpp
  tasks/seq/nasedkin_e_matrix_column_max_value/func_tests/main.cpp
  tasks/seq/nasedkin_e_matrix_column_max_value/include/ops_seq.hpp
  tasks/seq/nasedkin_e_matrix_column_max_value/perf_tests/main.cpp
  tasks/seq/nasedkin_e_matrix_column_max_value/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#148 Малышев Владимир. Задача 1. Вариант 21. Метод интегрирования Монте-Карло
  tasks/mpi/malyshev_v_monte_carlo_integration/func_tests/main.cpp
  tasks/mpi/malyshev_v_monte_carlo_integration/include/ops_mpi.hpp
  tasks/mpi/malyshev_v_monte_carlo_integration/perf_tests/main.cpp
  tasks/mpi/malyshev_v_monte_carlo_integration/src/ops_mpi.cpp
  tasks/seq/malyshev_v_monte_carlo_integration/func_tests/main.cpp
  tasks/seq/malyshev_v_monte_carlo_integration/include/ops_seq.hpp
  tasks/seq/malyshev_v_monte_carlo_integration/perf_tests/main.cpp
  tasks/seq/malyshev_v_monte_carlo_integration/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#236 fix Revert "Коровин Никита. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы."
  tasks/mpi/korovin_n_min_val_row_matrix/func_tests/main.cpp
  tasks/mpi/korovin_n_min_val_row_matrix/include/ops_mpi.hpp
  tasks/mpi/korovin_n_min_val_row_matrix/perf_tests/main.cpp
  tasks/mpi/korovin_n_min_val_row_matrix/src/ops_mpi.cpp
  tasks/seq/korovin_n_min_val_row_matrix/func_tests/main.cpp
  tasks/seq/korovin_n_min_val_row_matrix/include/ops_seq.hpp
  tasks/seq/korovin_n_min_val_row_matrix/perf_tests/main.cpp
  tasks/seq/korovin_n_min_val_row_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#202 Шульпин Илья. Задача 1. Вариант 21. Интегрирование методом Монте-Карло
  tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
  tasks/mpi/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
  tasks/mpi/shulpin_monte_carlo_integration/perf_tests/main.cpp
  tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
  tasks/seq/shulpin_monte_carlo_integration/func_tests/main.cpp
  tasks/seq/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
  tasks/seq/shulpin_monte_carlo_integration/perf_tests/main.cpp
  tasks/seq/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
Labels: approved - Alexander, approved - Arseniy

#268 Дерябин Максим. Задача 1. Вариант 23. Подсчет частоты символа в строке
  tasks/mpi/deryabin_m_symbol_frequency/func_tests/main.cpp
  tasks/mpi/deryabin_m_symbol_frequency/include/ops_mpi.hpp
  tasks/mpi/deryabin_m_symbol_frequency/perf_tests/main.cpp
  tasks/mpi/deryabin_m_symbol_frequency/src/ops_mpi.cpp
  tasks/seq/deryabin_m_symbol_frequency/func_tests/main.cpp
  tasks/seq/deryabin_m_symbol_frequency/include/ops_seq.hpp
  tasks/seq/deryabin_m_symbol_frequency/perf_tests/main.cpp
  tasks/seq/deryabin_m_symbol_frequency/src/ops_seq.cpp
Labels: approved - Arseniy

#231 Варфоломеев Григорий. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
  tasks/mpi/varfolomeev_g_matrix_max_rows_vals/func_tests/main.cpp
  tasks/mpi/varfolomeev_g_matrix_max_rows_vals/include/ops_mpi.hpp
  tasks/mpi/varfolomeev_g_matrix_max_rows_vals/perf_tests/main.cpp
  tasks/mpi/varfolomeev_g_matrix_max_rows_vals/src/ops_mpi.cpp
  tasks/seq/varfolomeev_g_matrix_max_rows_vals/func_tests/main.cpp
  tasks/seq/varfolomeev_g_matrix_max_rows_vals/include/ops_seq.hpp
  tasks/seq/varfolomeev_g_matrix_max_rows_vals/perf_tests/main.cpp
  tasks/seq/varfolomeev_g_matrix_max_rows_vals/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#197 Поликанов Виталий. Задание 1. Вариант 3. Максимальное значение в векторе
  tasks/mpi/polikanov_v_max_of_vector_elements/func_tests/main.cpp
  tasks/mpi/polikanov_v_max_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/polikanov_v_max_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/polikanov_v_max_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/polikanov_v_max_of_vector_elements/func_tests/main.cpp
  tasks/seq/polikanov_v_max_of_vector_elements/include/ops_seq.hpp
  tasks/seq/polikanov_v_max_of_vector_elements/perf_tests/main.cpp
  tasks/seq/polikanov_v_max_of_vector_elements/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#269 Revert "Алпутов Иван. Задача 1. Вариант 8. Найти наиболее отличающиеся по значению соседние элементы вектора."
  tasks/mpi/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
  tasks/mpi/alputov_i_most_different_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/alputov_i_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/alputov_i_most_different_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/alputov_i_most_different_neighbor_elements/func_tests/main.cpp
  tasks/seq/alputov_i_most_different_neighbor_elements/include/ops_seq.hpp
  tasks/seq/alputov_i_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/seq/alputov_i_most_different_neighbor_elements/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#168 Леонтьев Никита. Задача 1. Вариант 1. Сумма элементов вектора.
  tasks/mpi/leontev_n_vector_sum/func_tests/main.cpp
  tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
  tasks/mpi/leontev_n_vector_sum/perf_tests/main.cpp
  tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
  tasks/seq/leontev_n_vector_sum/func_tests/main.cpp
  tasks/seq/leontev_n_vector_sum/include/ops_seq.hpp
  tasks/seq/leontev_n_vector_sum/perf_tests/main.cpp
  tasks/seq/leontev_n_vector_sum/src/ops_seq.cpp
Labels: wait approvers, approved - Alexander, approved - Arseniy

#169 Шкуринская Елена. Задача 1. Вариант 25. Подсчет числа предложений в с…
  tasks/mpi/shkurinskaya_e_count_sentences/func_tests/main.cpp
  tasks/mpi/shkurinskaya_e_count_sentences/include/ops_mpi.hpp
  tasks/mpi/shkurinskaya_e_count_sentences/perf_tests/main.cpp
  tasks/mpi/shkurinskaya_e_count_sentences/src/ops_mpi.cpp
  tasks/seq/shkurinskaya_e_count_sentences/func_tests/main.cpp
  tasks/seq/shkurinskaya_e_count_sentences/include/ops_seq.hpp
  tasks/seq/shkurinskaya_e_count_sentences/perf_tests/main.cpp
  tasks/seq/shkurinskaya_e_count_sentences/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#237 Шарамыгина Ирина. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
  tasks/mpi/sharamygina_i_most_different_neighbor_elements/func_tests/main.cpp
  tasks/mpi/sharamygina_i_most_different_neighbor_elements/include/ops_mpi.hpp
  tasks/mpi/sharamygina_i_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/sharamygina_i_most_different_neighbor_elements/src/ops_mpi.cpp
  tasks/seq/sharamygina_i_most_different_neighbor_elements/func_tests/main.cpp
  tasks/seq/sharamygina_i_most_different_neighbor_elements/include/ops_seq.hpp
  tasks/seq/sharamygina_i_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/seq/sharamygina_i_most_different_neighbor_elements/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#174 Махов Михаил. Задача 1. Вариант 27. Подсчет числа несовпадающих символов двух строк.
  tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/func_tests/main.cpp
  tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/include/ops_mpi.hpp
  tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/perf_tests/main.cpp
  tasks/mpi/makhov_m_num_of_diff_elements_in_two_str/src/ops_mpi.cpp
  tasks/seq/makhov_m_num_of_diff_elements_in_two_str/func_tests/main.cpp
  tasks/seq/makhov_m_num_of_diff_elements_in_two_str/include/ops_seq.hpp
  tasks/seq/makhov_m_num_of_diff_elements_in_two_str/perf_tests/main.cpp
  tasks/seq/makhov_m_num_of_diff_elements_in_two_str/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#222 Капустин Иван. Задача 1. Вариант 16. Нахождение максимальных элементов по столбцам матрицы.
  tasks/mpi/kapustin_i_max_cols/func_tests/main.cpp
  tasks/mpi/kapustin_i_max_cols/include/avg_mpi.hpp
  tasks/mpi/kapustin_i_max_cols/perf_tests/main.cpp
  tasks/mpi/kapustin_i_max_cols/src/avg_mpi.cpp
  tasks/seq/kapustin_i_max_cols/func_tests/main.cpp
  tasks/seq/kapustin_i_max_cols/include/avg_seq.hpp
  tasks/seq/kapustin_i_max_cols/perf_tests/main.cpp
  tasks/seq/kapustin_i_max_cols/src/avg_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#230 Чернова Наталья. Задача 1. Вариант 24. Подсчет числа слов в строке
  tasks/mpi/chernova_n_word_count/func_tests/main.cpp
  tasks/mpi/chernova_n_word_count/include/ops_mpi.hpp
  tasks/mpi/chernova_n_word_count/perf_tests/main.cpp
  tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
  tasks/seq/chernova_n_word_count/func_tests/main.cpp
  tasks/seq/chernova_n_word_count/include/ops_seq.hpp
  tasks/seq/chernova_n_word_count/perf_tests/main.cpp
  tasks/seq/chernova_n_word_count/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#234 Федоров Матвей. Задача1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора
  tasks/mpi/fyodorov_m_num_of_orderly_violations/func_tests/main.cpp
  tasks/mpi/fyodorov_m_num_of_orderly_violations/include/ops_mpi.hpp
  tasks/mpi/fyodorov_m_num_of_orderly_violations/perf_tests/main.cpp
  tasks/mpi/fyodorov_m_num_of_orderly_violations/src/ops_mpi.cpp
  tasks/seq/fyodorov_m_num_of_orderly_violations/func_tests/main.cpp
  tasks/seq/fyodorov_m_num_of_orderly_violations/include/ops_seq.hpp
  tasks/seq/fyodorov_m_num_of_orderly_violations/perf_tests/main.cpp
  tasks/seq/fyodorov_m_num_of_orderly_violations/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#258 Вершинина Александра. Задача 1. Вариант 21. Интегрирование – метод Монте-Карло
  tasks/mpi/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
  tasks/mpi/vershinina_a_integration_the_monte_carlo_method/include/ops_mpi.hpp
  tasks/mpi/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
  tasks/mpi/vershinina_a_integration_the_monte_carlo_method/src/ops_mpi.cpp
  tasks/seq/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
  tasks/seq/vershinina_a_integration_the_monte_carlo_method/include/ops_seq.hpp
  tasks/seq/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
  tasks/seq/vershinina_a_integration_the_monte_carlo_method/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#259 Комшина Дарья. Задача 1. Вариант 4. Минимальное значение элемента в векторе.
  tasks/mpi/komshina_d_min_of_vector_elements/func_tests/main.cpp
  tasks/mpi/komshina_d_min_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/komshina_d_min_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/komshina_d_min_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/komshina_d_min_of_vector_elements/func_tests/main.cpp
  tasks/seq/komshina_d_min_of_vector_elements/include/ops_seq.hpp
  tasks/seq/komshina_d_min_of_vector_elements/perf_tests/main.cpp
  tasks/seq/komshina_d_min_of_vector_elements/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy

#163 [CI] Cancel workflows for stale commits automatically
  .github/workflows/main.yml
  .github/workflows/static-analysis-pr.yml
  .github/workflows/static-analysis.yml
Labels: enhancement, approved - Alexander, approved - Arseniy

#257 Владимирова Юлия. Задача 1. Вариант 13. Максимальное значение элементов матрицы. (2)
  tasks/mpi/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
  tasks/mpi/vladimirova_j_max_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/vladimirova_j_max_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
  tasks/seq/vladimirova_j_max_of_vector_elements/include/ops_seq.hpp
  tasks/seq/vladimirova_j_max_of_vector_elements/perf_tests/main.cpp
  tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#254 Golovkin Maksim. Task№1. Var №19. integration_rectangular_method
  tasks/mpi/golovkin_integration_rectangular_method/func_tests/main.cpp
  tasks/mpi/golovkin_integration_rectangular_method/include/ops_mpi.hpp
  tasks/mpi/golovkin_integration_rectangular_method/perf_tests/main.cpp
  tasks/mpi/golovkin_integration_rectangular_method/src/ops_mpi.cpp
  tasks/seq/golovkin_integration_rectangular_method/func_tests/main.cpp
  tasks/seq/golovkin_integration_rectangular_method/include/ops_seq.hpp
  tasks/seq/golovkin_integration_rectangular_method/perf_tests/main.cpp
  tasks/seq/golovkin_integration_rectangular_method/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#297 Revert "Revert "Revert "Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы"""
  tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
  tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
  tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
  tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
  tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
Labels: approved - Arseniy

#280 Васильев Сергей Задача 2 вариант 15 Ленточная горизонтальная схема
  tasks/mpi/vasilev_s_striped_horizontal_scheme/func_tests/main.cpp
  tasks/mpi/vasilev_s_striped_horizontal_scheme/include/ops_mpi.hpp
  tasks/mpi/vasilev_s_striped_horizontal_scheme/perf_tests/main.cpp
  tasks/mpi/vasilev_s_striped_horizontal_scheme/src/ops_mpi.cpp
  tasks/seq/vasilev_s_striped_horizontal_scheme/func_tests/main.cpp
  tasks/seq/vasilev_s_striped_horizontal_scheme/include/ops_seq.hpp
  tasks/seq/vasilev_s_striped_horizontal_scheme/perf_tests/main.cpp
  tasks/seq/vasilev_s_striped_horizontal_scheme/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#292 fix name perf test Коровин Никита. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.
  tasks/mpi/korovin_n_min_val_row_matrix/perf_tests/main.cpp
Labels: approved - Alexander, approved - Arseniy

#303 Revert. Шульпин Илья. Задача 1. Вариант 21. Интегрирование методом Монте-Карло
  tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
  tasks/mpi/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
  tasks/mpi/shulpin_monte_carlo_integration/perf_tests/main.cpp
  tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
  tasks/seq/shulpin_monte_carlo_integration/func_tests/main.cpp
  tasks/seq/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
  tasks/seq/shulpin_monte_carlo_integration/perf_tests/main.cpp
  tasks/seq/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
Labels: approved - Arseniy
