Repository learning-process/ppc-2024-autumn, pull requests merged in 2024-10, with the labels that each got.

#29 Хасаньянов Кирилл. Задача 1. Вариант 2. Среднее значение элементов вектора.
  tasks/mpi/khasanyanov_k_average_vector/func_tests/main.cpp
  tasks/mpi/khasanyanov_k_average_vector/include/avg_mpi.hpp
  tasks/mpi/khasanyanov_k_average_vector/perf_tests/main.cpp
  tasks/mpi/khasanyanov_k_average_vector/src/avg_mpi.cpp
  tasks/seq/khasanyanov_k_average_vector/func_tests/main.cpp
  tasks/seq/khasanyanov_k_average_vector/include/avg_seq.hpp
  tasks/seq/khasanyanov_k_average_vector/perf_tests/main.cpp
  tasks/seq/khasanyanov_k_average_vector/src/avg_seq.cpp
Labels: on review

#35 Лопатин Илья. Задача 1. Вариант 24. Подсчёт числа слов в строке.
  tasks/mpi/lopatin_i_count_words/func_tests/countWordsFuncTests.cpp
  tasks/mpi/lopatin_i_count_words/include/countWordsMPIHeader.hpp
  tasks/mpi/lopatin_i_count_words/perf_tests/countWordsPerfTests.cpp
  tasks/mpi/lopatin_i_count_words/src/countWordsMPI.cpp
  tasks/seq/lopatin_i_count_words/func_tests/countWordsFuncTests.cpp
  tasks/seq/lopatin_i_count_words/include/countWordsSeqHeader.hpp
  tasks/seq/lopatin_i_count_words/perf_tests/countWordsPerfTests.cpp
  tasks/seq/lopatin_i_count_words/src/countWordsSeq.cpp
Labels: on review

#15 Куракин Матвей. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/include/ops_mpi.hpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/perf_tests/main.cpp
  tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/ops_mpi.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/include/ops_seq.hpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/perf_tests/main.cpp
  tasks/seq/kurakin_m_min_values_by_rows_matrix/src/ops_seq.cpp
Labels: on review

#37 Мухина Маргарита. Задача 1. Вариант 4. Минимальное значение элементов вектора.
  tasks/mpi/muhina_m_min_of_vector_elements/func_tests/main.cpp
  tasks/mpi/muhina_m_min_of_vector_elements/include/ops_mpi.hpp
  tasks/mpi/muhina_m_min_of_vector_elements/perf_tests/main.cpp
  tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
  tasks/seq/muhina_m_min_of_vector_elements/func_tests/main.cpp
  tasks/seq/muhina_m_min_of_vector_elements/include/ops_seq.hpp
  tasks/seq/muhina_m_min_of_vector_elements/perf_tests/main.cpp
  tasks/seq/muhina_m_min_of_vector_elements/src/ops_seq.cpp
Labels: on review

#46 Филатьева Елизавета. Задача 1. Вариант 25. Подсчет числа предложений в строке.
  tasks/mpi/filateva_e_number_sentences_line/func_tests/main.cpp
  tasks/mpi/filateva_e_number_sentences_line/include/ops_mpi.hpp
  tasks/mpi/filateva_e_number_sentences_line/perf_tests/main.cpp
  tasks/mpi/filateva_e_number_sentences_line/src/ops_mpi.cpp
  tasks/seq/filateva_e_number_sentences_line/func_tests/main.cpp
  tasks/seq/filateva_e_number_sentences_line/include/ops_seq.hpp
  tasks/seq/filateva_e_number_sentences_line/perf_tests/main.cpp
  tasks/seq/filateva_e_number_sentences_line/src/ops_seq.cpp
Labels: approved - Alexander, on review - Arseniy

#22 Черных Андрей. Задача 1. Вариант 5. Нахождение числа чередований знаков значений соседних элементов вектора.
  tasks/mpi/chernykh_a_num_of_alternations_signs/func_tests/main.cpp
  tasks/mpi/chernykh_a_num_of_alternations_signs/include/ops_mpi.hpp
  tasks/mpi/chernykh_a_num_of_alternations_signs/perf_tests/main.cpp
  tasks/mpi/chernykh_a_num_of_alternations_signs/src/ops_mpi.cpp
  tasks/seq/chernykh_a_num_of_alternations_signs/func_tests/main.cpp
  tasks/seq/chernykh_a_num_of_alternations_signs/include/ops_seq.hpp
  tasks/seq/chernykh_a_num_of_alternations_signs/perf_tests/main.cpp
  tasks/seq/chernykh_a_num_of_alternations_signs/src/ops_seq.cpp
Labels: wait approvers

#43 Филатьев Владислав. Задача 1. Вариант 10. Сумма элементов матрицы.
  tasks/mpi/filatev_v_sum_of_matrix_elements/func_tests/main.cpp
  tasks/mpi/filatev_v_sum_of_matrix_elements/include/ops_mpi.hpp
  tasks/mpi/filatev_v_sum_of_matrix_elements/perf_tests/main.cpp
  tasks/mpi/filatev_v_sum_of_matrix_elements/src/ops_mpi.cpp
  tasks/seq/filatev_v_sum_of_matrix_elements/func_tests/main.cpp
  tasks/seq/filatev_v_sum_of_matrix_elements/include/ops_seq.hpp
  tasks/seq/filatev_v_sum_of_matrix_elements/perf_tests/main.cpp
  tasks/seq/filatev_v_sum_of_matrix_elements/src/ops_seq.cpp
Labels: wait approvers

#32 Резанцева Анастасия. Задача 1. Вариант 9. Скалярное произведение векторов.
  tasks/mpi/rezantseva_a_vector_dot_product/func_tests/main.cpp
  tasks/mpi/rezantseva_a_vector_dot_product/include/ops_mpi.hpp
  tasks/mpi/rezantseva_a_vector_dot_product/perf_tests/main.cpp
  tasks/mpi/rezantseva_a_vector_dot_product/src/ops_mpi.cpp
  tasks/seq/rezantseva_a_vector_dot_product/func_tests/main.cpp
  tasks/seq/rezantseva_a_vector_dot_product/include/ops_seq.hpp
  tasks/seq/rezantseva_a_vector_dot_product/perf_tests/main.cpp
  tasks/seq/rezantseva_a_vector_dot_product/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#50 Коробейников Арсений. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
  tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
  tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/include/ops_mpi_korobeinikov.hpp
  tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/perf_tests/main_korobeinikov.cpp
  tasks/mpi/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_mpi_korobeinikov.cpp
  tasks/seq/korobeinikov_a_max_elements_in_rows_of_matrix/func_tests/main_korobeinikov.cpp
  tasks/seq/korobeinikov_a_max_elements_in_rows_of_matrix/include/ops_seq_korobeinikov.hpp
  tasks/seq/korobeinikov_a_max_elements_in_rows_of_matrix/perf_tests/main_korobeinikov.cpp
  tasks/seq/korobeinikov_a_max_elements_in_rows_of_matrix/src/ops_seq_korobeinikov.cpp
Labels: on review - Alexander, approved - Arseniy

#49 Бесхмельнова Ксения. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора.
  tasks/mpi/beskhmelnova_k_most_different_neighbor_elements/func_tests/main.cpp
  tasks/mpi/beskhmelnova_k_most_different_neighbor_elements/include/mpi.hpp
  tasks/mpi/beskhmelnova_k_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/mpi/beskhmelnova_k_most_different_neighbor_elements/src/mpi.cpp
  tasks/seq/beskhmelnova_k_most_different_neighbor_elements/func_tests/main.cpp
  tasks/seq/beskhmelnova_k_most_different_neighbor_elements/include/seq.hpp
  tasks/seq/beskhmelnova_k_most_different_neighbor_elements/perf_tests/main.cpp
  tasks/seq/beskhmelnova_k_most_different_neighbor_elements/src/seq.cpp
Labels: approved - Alexander, approved - Arseniy

#33 Шурыгин Сергей. Задача №1. Вариант №16. Нахождение максимальных значений по столбцам матрицы
  tasks/mpi/Shurygin_S_max_po_stolbam_matrix/func_tests/main.cpp
  tasks/mpi/Shurygin_S_max_po_stolbam_matrix/include/ops_mpi.hpp
  tasks/mpi/Shurygin_S_max_po_stolbam_matrix/perf_tests/main.cpp
  tasks/mpi/Shurygin_S_max_po_stolbam_matrix/src/ops_mpi.cpp
  tasks/seq/Shurygin_S_max_po_stolbam_matrix/func_tests/main.cpp
  tasks/seq/Shurygin_S_max_po_stolbam_matrix/include/ops_seq.hpp
  tasks/seq/Shurygin_S_max_po_stolbam_matrix/perf_tests/main.cpp
  tasks/seq/Shurygin_S_max_po_stolbam_matrix/src/ops_seq.cpp
Labels: wait approvers

#53 Колоколова Дарья. Задача 1. Вариант 15. Нахождение максимальных значений по строкам матрицы.
  tasks/mpi/kolokolova_d_max_of_row_matrix/func_tests/main.cpp
  tasks/mpi/kolokolova_d_max_of_row_matrix/include/ops_mpi.hpp
  tasks/mpi/kolokolova_d_max_of_row_matrix/perf_tests/main.cpp
  tasks/mpi/kolokolova_d_max_of_row_matrix/src/ops_mpi.cpp
  tasks/seq/kolokolova_d_max_of_row_matrix/func_tests/main.cpp
  tasks/seq/kolokolova_d_max_of_row_matrix/include/ops_seq.hpp
  tasks/seq/kolokolova_d_max_of_row_matrix/perf_tests/main.cpp
  tasks/seq/kolokolova_d_max_of_row_matrix/src/ops_seq.cpp
Labels: on review - Alexander, approved - Arseniy

#41 Лысов Иван. Задача 1. Вариант 20. Интегрирование – метод трапеций.
  tasks/mpi/lysov_i_integration_the_trapezoid_method/func_tests/main.cpp
  tasks/mpi/lysov_i_integration_the_trapezoid_method/include/ops_mpi.hpp
  tasks/mpi/lysov_i_integration_the_trapezoid_method/perf_tests/main.cpp
  tasks/mpi/lysov_i_integration_the_trapezoid_method/src/ops_mpi.cpp
  tasks/seq/lysov_i_integration_the_trapezoid_method/func_tests/main.cpp
  tasks/seq/lysov_i_integration_the_trapezoid_method/include/ops_seq.hpp
  tasks/seq/lysov_i_integration_the_trapezoid_method/perf_tests/main.cpp
  tasks/seq/lysov_i_integration_the_trapezoid_method/src/ops_seq.cpp
Labels: approved - Alexander, approved - Arseniy
